<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
    $_product = $block->getProduct();
    $_id = $_product->getId();
?>
<?php if ($_product->getCanShowPrice() !== false):?>
    <div class="price-box">
    <?php if (($_min = $block->getMinAmount()) && ($_max = $block->getMaxAmount()) && ($_min == $_max)): ?>
        <span class="price" id="product-price-<?= /* @escapeNotVerified */ $_id ?><?= /* @escapeNotVerified */ $block->getIdSuffix() ?>">
            <?= /* @escapeNotVerified */ $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_min, true, false) ?>
        </span>
    <?php elseif (($_min = $block->getMinAmount()) && $_min != 0): ?>
        <span class="price-label"><?= /* @escapeNotVerified */ __('From') ?></span>
        <span class="price" id="min-product-price-<?= /* @escapeNotVerified */ $_id ?><?= /* @escapeNotVerified */ $block->getIdSuffix() ?>">
            <?= /* @escapeNotVerified */ $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_min, true, false) ?>
        </span>
    <?php endif; ?>
    </div>
<?php endif; ?>
