<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<button type="button" title="<?= /* @escapeNotVerified */ __('Delete Wish List') ?>" data-wishlist-delete='{"wishlistId":"<?= /* @escapeNotVerified */ $block->getWishlistInstance()->getId() ?>", "redirectUrl":"<?= /* @escapeNotVerified */ $block->getRedirectUrl() ?>", "deleteUrl":"<?= /* @escapeNotVerified */ $block->getDeleteUrl() ?>"}' class="action remove"><span><?= /* @escapeNotVerified */ __('Delete Wish List') ?></span></button>
