<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $entity = $block->getEntity() ?>

<?php if ($entity): ?>
    <div class="block block-giftregistry-shared">
        <div class="block-content">
            <dl class="item-options giftregistry-description">
                <?php foreach ($block->getAttributesToDisplay() as $attributeInfo): ?>
                    <dt class="item-title"><?= /* @escapeNotVerified */ $attributeInfo['title'] ?></dt>
                    <dd class="item-value"><?= /* @escapeNotVerified */ $attributeInfo['value'] ?></dd>
                <?php endforeach; ?>
            </dl>
        </div>
    </div>
    <?= $block->getChildHtml('giftregistry_items') ?>
<?php endif; ?>
<div class="actions-toolbar">
    <div class="secondary">
        <a href="<?= $block->escapeUrl($block->getSearchBackUrl()) ?>" class="action back"><span><?= /* @escapeNotVerified */ __('Back') ?></span></a>
    </div>
</div>
