<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Catalog Event category page
 *
 * @var $block \Magento\CatalogEvent\Block\Event\Lister
 */
?>
<div class="block widget block-event">
    <div id="<?= $block->getHtmlId() ?>" data-mage-init='{"carousel": {"pageSize": <?= /* @escapeNotVerified */ $block->getPageSize() ?>, "scrollSize": <?= /* @escapeNotVerified */ $block->getScrollSize() ?>, "toggleInit": true}}' class="block-content"<?php if ($block->hasWidth()): ?> style="width: <?= (int)$block->getWidth() ?>px !important;" <?php endif;?>>
        <div data-slide-button="slide-button" class="action backward" title="<?= /* @escapeNotVerified */ __('Previous') ?>"><span>&lt;</span></div>
        <div data-slider-panel="slider-panel" class="slider-panel"<?php if ($block->hasWidth()): ?> style="width: <?= (int)$block->getWidth() ?>px !important;" <?php endif;?>>
            <ul data-slider="slider" class="slider">
                <?php foreach ($block->getEvents() as $_event): ?>
                    <?php $_category = $_event->getCategory(); ?>
                    <li data-slider-item="slider-item" class="item">
                        <a class="action show" href="<?= /* @escapeNotVerified */ $block->getCategoryUrl($_category) ?>"
                           title="<?= $block->escapeHtml($_category->getName()) ?>">
                            <?php if ($block->getEventImageUrl($_event)): ?>
                                <img src="<?= /* @escapeNotVerified */ $block->getEventImageUrl($_event) ?>"
                                     title="<?= $block->escapeHtml($_category->getName()) ?>"
                                     alt="<?= $block->escapeHtml($_category->getName()) ?>"/>
                            <?php else: ?>
                                <span
                                    class="category-name"><?= $block->escapeHtml($_category->getName()) ?></span>
                            <?php endif; ?>
                        </a>
                        <div class="box box-event <?= /* @escapeNotVerified */ $_event->getStatus() ?>">
                            <strong class="box-title">
                                <span><?= /* @escapeNotVerified */ $block->getStatusText($_event) ?></span>
                            </strong>
                            <div class="box-content">
                                <?php switch ($_event->getStatus()):
                                    case \Magento\CatalogEvent\Model\Event::STATUS_UPCOMING: ?>
                                        <div class="dates">
                                            <div class="start">
                                                <strong class="date"><?= /* @escapeNotVerified */ $block->getEventDate('start', $_event) ?></strong>
                                                <span class="time"><?= /* @escapeNotVerified */ $block->getEventTime('start', $_event, 'hh a zzz') ?></span>
                                            </div>
                                            <div class="end">
                                                <strong class="date"><?= /* @escapeNotVerified */ $block->getEventDate('end', $_event) ?></strong>
                                                <span class="time"><?= /* @escapeNotVerified */ $block->getEventTime('end', $_event, 'hh a zzz') ?></span>
                                            </div>
                                        </div>
                                        <a class="action event" href="<?= /* @escapeNotVerified */ $block->getCategoryUrl($_category) ?>"><span><?= /* @escapeNotVerified */ __('Preview Sale') ?></span></a>
                                        <?php break;
                                    case \Magento\CatalogEvent\Model\Event::STATUS_OPEN: ?>
                                        <ul class="ticker"
                                            id="<?= $block->getHtmlId() ?>-event-ticker-<?= /* @escapeNotVerified */ $_event->getId() ?>"
                                            data-mage-init='{"ticker":{"secondsToClose": <?= /* @escapeNotVerified */ $block->getSecondsToClose($_event) ?>, "eventEndTimeUTC": <?= /* @noEscape */ $block->getEndTimeUTC($_event) ?>}}'>
                                            <li class="days">
                                                <span data-container="days" class="value">&nbsp;</span>
                                                <span class="label"><?= /* @escapeNotVerified */ __('Days') ?></span>
                                            </li>
                                            <li class="hour">
                                                <span data-container="hour" class="value">&nbsp;</span>
                                                <span class="label"><?= /* @escapeNotVerified */ __('Hrs') ?></span>
                                            </li>
                                            <li class="minute">
                                                <span data-container="minute" class="value">&nbsp;</span>
                                                <span class="label"><?= /* @escapeNotVerified */ __('Mins') ?></span>
                                            </li>
                                            <li class="second">
                                                <span data-container="second" class="value">&nbsp;</span>
                                                <span class="label"><?= /* @escapeNotVerified */ __('Sec') ?></span>
                                            </li>
                                        </ul>
                                        <a class="action event" href="<?= /* @escapeNotVerified */ $block->getCategoryUrl($_category) ?>"><span><?= /* @escapeNotVerified */ __('Go To Sale') ?></span></a>
                                        <?php break;
                                    case \Magento\CatalogEvent\Model\Event::STATUS_CLOSED: ?>
                                        <div class="dates">
                                            <div class="start">
                                                <strong class="date"><?= /* @escapeNotVerified */ $block->getEventDate('start', $_event) ?></strong>
                                                <span class="time"><?= /* @escapeNotVerified */ $block->getEventTime('start', $_event, 'hh a zzz') ?></span>
                                            </div>
                                            <div class="end">
                                                <strong class="date"><?= /* @escapeNotVerified */ $block->getEventDate('end', $_event) ?></strong>
                                                <span class="time"><?= /* @escapeNotVerified */ $block->getEventTime('end', $_event, 'hh a zzz') ?></span>
                                            </div>
                                        </div>
                                        <a class="action event" href="<?= /* @escapeNotVerified */ $block->getCategoryUrl($_category) ?>"><span><?= /* @escapeNotVerified */ __('View Sale') ?></span></a>
                                    <?php break; ?>
                                <?php endswitch; ?>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div data-slide-button="slide-button" class="action forward" title="<?= /* @escapeNotVerified */ __('Next') ?>"><span>&gt;</span></div>
    </div>
</div>
