<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php if (!$block->isUserNotAllowSaveCookie()) { ?>
    <?php
    /** @var \Magento\GoogleTagManager\Block\Adminhtml\Ga $block */
    $accountType = $block->getConfig(\Magento\GoogleTagManager\Helper\Data::XML_PATH_TYPE);
    $gtmAccountId = $block->getConfig(\Magento\GoogleTagManager\Helper\Data::XML_PATH_CONTAINER_ID);
    $gapAccountId = $block->getConfig(\Magento\GoogleTagManager\Helper\Data::XML_PATH_ACCOUNT) ;
    switch ($accountType) {
        case \Magento\GoogleTagManager\Helper\Data::TYPE_TAG_MANAGER:
            if (!empty($gtmAccountId)) { ?>
                <!-- GOOGLE TAG MANAGER -->
                <noscript>
                    <iframe src="https://www.googletagmanager.com/ns.html?id=<?= /* @escapeNotVerified */ $gtmAccountId ?>" height="0" width="0"
                            style="display:none;visibility:hidden"></iframe>
                </noscript>
                <script>
                    //<![CDATA[
                    (function (w, d, s, l, i) {
                        w[l] = w[l] || [];
                        w[l].push({'gtm.start': new Date().getTime(), event: 'gtm.js'});
                        var f = d.getElementsByTagName(s)[0];
                        var j = d.createElement(s);
                        var dl = l != 'dataLayer' ? '&l=' + l : '';
                        j.async = true;
                        j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
                        f.parentNode.insertBefore(j, f);
                    })(window, document, 'script', 'dataLayer', '<?= /* @escapeNotVerified */ $gtmAccountId ?>');

                    dataLayer.push({
                        'ecommerce': {'currencyCode': '<?= /* @escapeNotVerified */ $block->getStoreCurrencyCode() ?>'}
                    });
                    <?= /* @escapeNotVerified */ $block->getOrdersData() ?>
                    //]]>
                </script>
                <!-- END GOOGLE TAG MANAGER -->
            <?php
            }
            break;
        case \Magento\GoogleTagManager\Helper\Data::TYPE_UNIVERSAL:
            if (!empty($gapAccountId)) {
                ?>
                <!-- BEGIN NEW GOOGLE UNIVERSAL CODE -->
                <script>
                    //<![CDATA[
                    (function (i, s, o, g, r, a, m) {
                        i['GoogleAnalyticsObject'] = r;
                        i[r] = i[r] || function () {
                            (i[r].q = i[r].q || []).push(arguments)
                        }, i[r].l = 1 * new Date();
                        a = s.createElement(o),
                            m = s.getElementsByTagName(o)[0];
                        a.async = 1;
                        a.src = g;
                        m.parentNode.insertBefore(a, m)
                    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

                    ga('create', '<?= /* @escapeNotVerified */ $gapAccountId ?>', 'auto');
                    <?= /* @escapeNotVerified */ $block->getAnonymizationCode() ?>
                    ga('send', 'pageview');

                    dataLayer.push({
                        'ecommerce': {'currencyCode': '<?= /* @escapeNotVerified */ $block->getStoreCurrencyCode() ?>'}
                    });
                    <?= /* @escapeNotVerified */ $block->getOrdersData() ?>
                    //]]>
                </script>
                <!-- END NEW GOOGLE UNIVERSAL CODE -->
            <?php
            }
            break;
    }
}
