<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<script>
require(['prototype'], function(){

//<![CDATA[
OptionTemplateCountry =
    '<div class="field field-region">'+
        '<label class="label" for=""><span><?= /* @escapeNotVerified */ __('Show Region') ?></label>'+
        '<div class="control"><?= $block->getRegionShowSelectHtml() ?></div>'+
    '</div>';

selectCountryType = {
    add : function(data) {
        if (data.show_region) {
            $A($(data.prefix+'_attribute_'+data.id+'_show_region').options).each(function(option){
                if (option.value==data.show_region) option.selected = true;
           });
        }
    }
}
//]]>

});
</script>
