<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
$_element = $block->getElement();
?>
<div class="popup-window">
<?php if ($_element->getFieldsetContainerId()): ?>
<div id="<?= /* @escapeNotVerified */ $_element->getFieldsetContainerId() ?>">
<?php endif; ?>
<?php if ($_element->getLegend()): ?>
<div class="popup-window-title">
    <div class="actions"><?= /* @escapeNotVerified */ $_element->getHeaderBar() ?></div>
    <div class="title"><?= /* @escapeNotVerified */ $_element->getLegend() ?></div>
</div>
<?php endif; ?>
<?php if (!$_element->getNoContainer()): ?>
    <div class="popup-window-content">
        <div class="<?= /* @escapeNotVerified */ $_element->getClass() ?>" id="<?= $_element->getHtmlId() ?>">
<?php endif; ?>
        <?php if ($_element->getComment()): ?>
            <p class="comment"><?= $block->escapeHtml($_element->getComment()) ?></p>
        <?php endif; ?>
        <?php if ($_element->hasHtmlContent()): ?>
            <?= $_element->getHtmlContent() ?>
        <?php else: ?>
            <?= $_element->getChildrenHtml() ?>
        <?php endif; ?>
    <?= $_element->getSubFieldsetHtml() ?>
<?php if (!$_element->getNoContainer()): ?>
        </div>
    </div>

    <div class="popup-window-buttons-set">
        <?= /* @escapeNotVerified */ $_element->getCancelButton() ?>
        <?= /* @escapeNotVerified */ $_element->getOkButton() ?>
    </div>

<?php endif; ?>
<?php if ($_element->getFieldsetContainerId()): ?>
</div>
<?php endif; ?>
</div>
