<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php $_source  = $block->getSource() ?>
<?php $block->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getCustomerBalanceAmount()): ?>
    <tr>
        <td class="label">
            <?= /* @escapeNotVerified */ __('Store Credit') ?>
        </td>
        <td>
            <?= /* @escapeNotVerified */ $block->displayPrices(-$_source->getBaseCustomerBalanceAmount(), -$_source->getCustomerBalanceAmount()) ?>
        </td>
    </tr>
<?php endif; ?>
