<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ((float) $block->getSource()->getRewardPointsBalanceRefund()): ?>
    <tr>
        <td class="label"><strong><?= /* @escapeNotVerified */ __('Reward Points refunded to customer') ?></strong></td>
        <td><strong><?= /* @escapeNotVerified */ $block->getSource()->getRewardPointsBalanceRefund() ?></strong></td>
    </tr>
<?php endif; ?>
