<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $block->setPriceDataObject($block->getSource()) ?>

<?php if ((float) $block->getSource()->getRewardCurrencyAmount()): ?>
    <tr>
        <td class="label"><?= /* @escapeNotVerified */ $this->helper('Magento\Reward\Helper\Data')->formatReward($block->getSource()->getRewardPointsBalance()) ?></td>
        <td>
            <?= /* @escapeNotVerified */ $block->displayPrices(-$block->getSource()->getBaseRewardCurrencyAmount(), -$block->getSource()->getRewardCurrencyAmount()) ?>
        </td>
    </tr>
<?php endif; ?>
