<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_item = $block->getItem()?>
<tr>
    <td data-th="<?= $block->escapeHtml(__('Product')) ?>" class="col product">
        <?php if ($block->hasProductUrl()):?>
        <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>" class="product-image" title="<?= $block->escapeHtml($block->getProductName()) ?>">
        <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'product_thumbnail_image')->toHtml() ?>
        <?php if ($block->hasProductUrl()):?>
        </a>
        <?php endif;?>

        <?php if ($block->hasProductUrl()):?>
            <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
        <?php else: ?>
            <?= $block->escapeHtml($block->getProductName()) ?>
        <?php endif; ?>
        <?php if ($_options = $block->getOptionList()):?>
        <dl class="product options list">
            <?php foreach ($_options as $_option) : ?>
            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="tooltip wrapper"<?php endif; ?>>
                <?= /* @escapeNotVerified */ $_formatedOptionValue['value'] ?>
                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                <div class="tooltip content">
                    <dl class="item-options">
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                        <dd><?= $block->escapeHtml($_formatedOptionValue['full_view']) ?></dd>
                    </dl>
                </div>
                <?php endif; ?>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif;?>
    </td>
    <td data-th="<?= $block->escapeHtml(__('Note')) ?>" class="col note">
        <div class="field note">
            <div class="control">
                <textarea name="items[<?= /* @escapeNotVerified */ $_item->getId() ?>][note]" rows="3" cols="10"><?= $block->escapeHtml($_item->getNote()) ?></textarea>
            </div>
        </div>
    </td>
    <td data-th="<?= $block->escapeHtml(__('Added On')) ?>" class="col date">
        <?= /* @escapeNotVerified */ $block->formatDate($_item->getAddedAt(), \IntlDateFormatter::MEDIUM) ?>
    </td>
    <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty">
        <div class="field qty">
            <div class="control">
                <input class="input-text qty" type="number" data-validate="{'validate-greater-than-zero':true}" name="items[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]" value="<?= /* @escapeNotVerified */ $_item->getQty()*1 ?>"/>
            </div>
        </div>
    </td>
    <td data-th="<?= $block->escapeHtml(__('Qty Fulfilled')) ?>" class="col fulfilled">
        <?= /* @escapeNotVerified */ $_item->getQtyFulfilled()*1 ?>
    </td>
    <td data-th="<?= $block->escapeHtml(__('Delete')) ?>" class="col actions">
        <div class="field choice">
            <input type="checkbox" class="checkbox" name="items[<?= /* @escapeNotVerified */ $_item->getItemId() ?>][delete]" value="1" />
        </div>
    </td>
</tr>
