<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Rma\Block\Returns\Returns */
?>
<?php $_returns = $block->getReturns(); ?>
<?php if ($_returns->getSize()): ?>
<div class="order-details-items rma">
    <?= $block->getChildHtml('info') ?>
    <div class="order-title"><strong><?= /* @escapeNotVerified */ __('My Returns') ?></strong></div>
    <div class="toolbar">
        <?= $block->getPagerHtml() ?>
    </div>
    <?= $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
    <?= $block->getChildHtml('info') ?>
    <div class="table-wrapper order-items returns">
        <table class="data table table-order-items returns" id="my-returns-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('My Returns') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Return #') ?></th>
                    <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Date') ?></th>
                    <th scope="col" class="col shipping"><?= /* @escapeNotVerified */ __('Ship From') ?></th>
                    <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Return Status') ?></th>
                    <th scope="col" class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php $_odd = ''; ?>
                <?php foreach ($_returns as $_return): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Return #')) ?>" class="col id" data-th="<?= $block->escapeHtml(__('Return #')) ?>"><?= /* @escapeNotVerified */ $_return->getIncrementId() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date" data-th="<?= $block->escapeHtml(__('Date')) ?>"><?= /* @escapeNotVerified */ $this->helper('Magento\Rma\Helper\Data')->getFormatedDate($_return->getDateRequested()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Ship From')) ?>" class="col shipping" data-th="<?= $block->escapeHtml(__('Ship From')) ?>"><?= $block->escapeHtml($_return->getCustomerName()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Return Status')) ?>" class="col status" data-th="<?= $block->escapeHtml(__('Return Status')) ?>"><?= $block->escapeHtml($_return->getStatusLabel()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions" data-th="<?= $block->escapeHtml(__('Actions')) ?>">
                        <a href="<?= /* @escapeNotVerified */ $block->getViewUrl($_return) ?>" class="cation view"><span><?= /* @escapeNotVerified */ __('View Return') ?></span></a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="toolbar">
        <?= $block->getPagerHtml() ?>
    </div>
</div>
<?php else: ?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You have placed no returns.') ?></span></div>
<?php endif ?>
