<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Rma\Block\Returns\Tracking\Package */ ?>
<?php  $_results = $block->getPackageInfo() ?>
<div class="page-title-wrapper">
    <h1 class="page-title"><span class="base"><?= /* @escapeNotVerified */ __('Packages') ?></span></h1>
    <div class="actions">
        <button class="action print" type="button" title="<?= /* @escapeNotVerified */ __('Print') ?>" onclick="setLocation('<?= /* @escapeNotVerified */ $block->getPrintPackageUrl() ?>');return false;"><span><?= /* @escapeNotVerified */ __('Print') ?></span></button>
        <button class="action close" type="button" title="<?= /* @escapeNotVerified */ __('Close Window') ?>" onclick="window.close(); window.opener.focus();"><span><?= /* @escapeNotVerified */ __('Close Window') ?></span></button>
    </div>
</div>
<div class="packed content">
<?php foreach ($block->getPackages() as $packageId => $package): ?>
        <?php $package = new \Magento\Framework\DataObject($package) ?>
        <?php $params = new \Magento\Framework\DataObject($package->getParams()) ?>
        <div class="block package info">
            <div class="title"><strong><?= /* @escapeNotVerified */ __('Package') . ' ' . $packageId ?></strong></div>
            <div class="table-wrapper">
                <table class="tracking popup data table">
                    <caption class="table-caption"><?= /* @escapeNotVerified */ __('Package') . ' ' . $packageId ?></caption>
                    <tbody>
                    <tr>
                        <th class="col type" scope="row"><?= /* @escapeNotVerified */ __('Type') ?></th>
                        <td class="col type"><?= /* @escapeNotVerified */ $block->getContainerTypeByCode($params->getContainer()) ?></td>
                        <th class="col length" scope="row"><?= /* @escapeNotVerified */ __('Length') ?></th>
                        <td class="col length"><?= /* @escapeNotVerified */ $params->getLength() . ' ' . $this->helper('Magento\Shipping\Helper\Carrier')->getMeasureDimensionName($params->getDimensionUnits()) ?></td>
                    </tr>
                    <tr>
                        <th class="col weight" scope="row"><?= /* @escapeNotVerified */ __('Total Weight') ?></th>
                        <td class="col weight"><?= /* @escapeNotVerified */ $params->getWeight() . ' ' . $this->helper('Magento\Shipping\Helper\Carrier')->getMeasureWeightName($params->getWeightUnits()) ?></td>
                        <th class="col width" scope="row"><?= /* @escapeNotVerified */ __('Width') ?></th>
                        <td class="col width"><?= /* @escapeNotVerified */ $params->getWidth() . ' ' . $this->helper('Magento\Shipping\Helper\Carrier')->getMeasureDimensionName($params->getDimensionUnits()) ?></td>
                    </tr>
                    <tr>
                        <th scope="row">&nbsp;</th>
                        <td>&nbsp;</td>
                        <th class="col height" scope="row"><?= /* @escapeNotVerified */ __('Height') ?></th>
                        <td class="col height"><?= /* @escapeNotVerified */ $params->getHeight() . ' ' . $this->helper('Magento\Shipping\Helper\Carrier')->getMeasureDimensionName($params->getDimensionUnits()) ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="block package items">
            <div class="title"><strong><?= /* @escapeNotVerified */ __('Items in the Package') ?></strong></div>
            <div class="table-wrapper">
                <table class="tracking popup data table">
                    <caption class="table-caption"><?= /* @escapeNotVerified */ __('Items in the Package') ?></caption>
                    <tr>
                        <th class="col product" scope="col"><?= /* @escapeNotVerified */ __('Product') ?></th>
                        <th class="col weight" scope="col"><?= /* @escapeNotVerified */ __('Weight') ?></th>
                        <th class="col qty" scope="col"><?= /* @escapeNotVerified */ __('Qty') ?></th>
                    </tr>
                    <?php foreach ($package->getItems() as $itemId => $item) : ?>
                        <?php $item = new \Magento\Framework\DataObject($item) ?>
                        <tr title="#">
                            <td data-th="<?= $block->escapeHtml(__('Product')) ?>" class="col product"> <?= /* @escapeNotVerified */ $item->getName() ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Weight')) ?>" class="col weight"><?= /* @escapeNotVerified */ $item->getWeight() ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty"><?= /* @escapeNotVerified */ $item->getQty()*1 ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
<?php endforeach; ?>
</div>
<div class="actions">
    <button class="action close" type="button" title="<?= /* @escapeNotVerified */ __('Close Window') ?>" onclick="window.close(); window.opener.focus();"><span><?= /* @escapeNotVerified */ __('Close Window') ?></span></button>
    <button class="action print" type="button" title="<?= /* @escapeNotVerified */ __('Print') ?>" onclick="setLocation('<?= /* @escapeNotVerified */ $block->getPrintPackageUrl() ?>');return false;"><span><?= /* @escapeNotVerified */ __('Print') ?></span></button>
</div>
