<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Logging\Block\Adminhtml\Details $block */
?>

<?php
$event = $block->getCurrentEvent();
?>

<div class="entry-edit form-inline">
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?= $block->escapeHtml(__('Admin User Data')) ?></span>
        </div>

        <div id="log_details_fieldset" class="field log-details">
            <table class="admin__table-secondary">
                <colgroup>
                    <col width="25%" />
                    <col />
                </colgroup>
                <tbody>
                <tr>
                    <th><?= $block->escapeHtml(__('Aggregated Information')) ?></th>
                    <td>
                        <?php
                        $eventInfo = $block->getEventInfo();
                        if (is_bool($eventInfo)) {
                            /* @noEscape */ echo($dataArray ? 'true' : 'false');
                        } elseif (is_array($eventInfo)) {
                            if (isset($eventInfo['general'])) {
                                if (!is_array($eventInfo['general'])) {
                                    $eventInfo['general'] = [$eventInfo['general']];
                                }
                                echo $block->escapeHtml(implode(', ', $eventInfo['general']));
                            }
                            ?>
                            <?php if (isset($eventInfo['additional'])): ?><br /><?php endif;
                            ?>
                            <?php
                            if (isset($eventInfo['additional'])) {
                                foreach ($eventInfo['additional'] as $modelName => $modelsData) {
                                    foreach ($modelsData as $mdoelId => $data) {
                                        echo $block->escapeHtml(implode(', ', $data));
                                    }
                                }
                            }
                        } else {
                            echo $block->escapeHtml($eventInfo);
                        }
                        ?>
                    </td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('Admin User ID')) ?></th>
                    <td>
                        <?php if ($block->getEventUser()) {
    ?>
                        #<?= $block->escapeHtml($event->getUserId());
    ?>
                        <?php 
} else {
    ?>
                        N/A
                        <?php 
} ?>
                    </td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('Admin User Name')) ?></th>
                    <td>
                        <?php if ($block->getEventUser()) {
    ?>
                        <a href="<?= $block->escapeUrl($block->getUrl('adminhtml/user/edit', ['user_id' => $event->getUserId()]));
    ?>"><?= $block->escapeHtml($event->getUser());
    ?></a>
                        <?php 
} else {
    ?>
                        <?= $block->escapeHtml($event->getUser());
    ?>
                        <?php 
} ?>
                    </td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('IP-Address')) ?></th>
                    <td><?= $block->escapeHtml($block->getEventIp()) ?></td>
                </tr>
                <?php if ($block->getEventXForwardedIp()) {
    ?>
                <tr>
                    <th><?= $block->escapeHtml(__('X-Forwarded For'));
    ?></th>
                    <td><?= $block->escapeHtml($block->getEventXForwardedIp());
    ?></td>
                </tr>
                    <?php 
} ?>
                <?php if ($block->getEventError()) {
    ?>
                <tr>
                    <th><?= $block->escapeHtml(__('Error Message'));
    ?></th>
                    <td><?= $block->escapeHtml($block->getEventError());
    ?></td>
                </tr>
                    <?php 
} ?>
                </tbody>
            </table>
        </div>
    </section>

    <?php if ($event->hasChanges()) {
    ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?= $block->escapeHtml(__('Related Changes')) ?></span>
        </div>

        <div class="field log-details-grid">
            <?= $block->getChildHtml('details_grid') ?>
        </div>
    </section>
    <?php 
} ?>
</div>
