<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="entry-edit form-inline giftcard-info-container" id="giftcard_info_container">
    <fieldset class="fieldset">
        <div class="admin__field field">
            <label class="label admin__field-label" for="giftcard_is_redeemable">
                <span><?= /* @escapeNotVerified */ __('Treat Balance as Store Credit') ?></span>
            </label>
            <div class="control">
                <select
                    <?php if ($block->isReadonly()):?>disabled="disabled"<?php endif;?>
                          id="giftcard_is_redeemable"
                          name="<?= /* @escapeNotVerified */ $block->getFieldPrefix() ?>[is_redeemable]"
                          class="admin__control-select">
                    <option value="1">
                        <?= /* @escapeNotVerified */ __('Yes') ?>
                    </option>
                    <option value="0"<?php if ($block->getFieldValue('is_redeemable') == 0): ?> selected="selected"<?php endif; ?>>
                        <?= /* @escapeNotVerified */ __('No') ?>
                    </option>
                </select>
                <input
                    type="hidden"
                    id="giftcard_is_redeemable_default"
                    value="<?= /* @escapeNotVerified */ $block->getConfigValue('is_redeemable') ?>" />
            </div>
            <div class="field-service" <?= /* @escapeNotVerified */ $block->getScopeValue('[GLOBAL]') ?>>
                <?php $_checked = ($block->getFieldValue('use_config_is_redeemable') || $block->IsNew()) ? 'checked="checked"' : '' ?>
                <input
                    type="hidden"
                    name="<?= /* @escapeNotVerified */ $block->getFieldPrefix() ?>[use_config_is_redeemable]"
                    value="0">
                <input
                    <?php if ($block->isReadonly()):?>disabled="disabled"<?php endif;?>
                    type="checkbox"
                    class="checkbox"
                    id="giftcard_use_config_is_redeemable"
                    name="<?= /* @escapeNotVerified */ $block->getFieldPrefix() ?>[use_config_is_redeemable]"
                    value="1"
                    <?= /* @escapeNotVerified */ $_checked ?>
                    onclick="toggleValueElements(this, this.up('.field'));toggleDefault('is_redeemable');"
                    />
                <label for="giftcard_use_config_is_redeemable" class="normal">
                    <?= /* @escapeNotVerified */ __('Use Config Settings') ?>
                </label>
                <script>
require(['prototype'], function(){

toggleValueElements($('giftcard_use_config_is_redeemable'), $('giftcard_use_config_is_redeemable').up('.field'));

});
</script>
            </div>
        </div>

        <div class="admin__field field">
            <label class="admin__field-label label" for="giftcard_lifetime">
                <span><?= /* @escapeNotVerified */ __('Lifetime (days)') ?></span>
            </label>
            <div class="control">
                <input
                    type="text"
                    <?php if ($block->isReadonly()):?>disabled="disabled"<?php endif;?>
                    class="input-text validate-number"
                    id="giftcard_lifetime"
                    name="<?= /* @escapeNotVerified */ $block->getFieldPrefix() ?>[lifetime]"
                    value="<?= /* @escapeNotVerified */ $block->getFieldValue('lifetime')*1 ?>"/>

                <input
                    type="hidden"
                    id="giftcard_lifetime_default"
                    value="<?= /* @escapeNotVerified */ $block->getConfigValue('lifetime') ?>" />
            </div>
            <div class="field-service" <?= /* @escapeNotVerified */ $block->getScopeValue('[GLOBAL]') ?>>
                <?php $_checked = ($block->getFieldValue('use_config_lifetime') || $block->IsNew()) ? 'checked="checked"' : '' ?>
                <input
                    type="hidden"
                    name="<?= /* @escapeNotVerified */ $block->getFieldPrefix() ?>[use_config_lifetime]"
                    value="0">
                <input
                    type="checkbox"
                    <?php if ($block->isReadonly()):?>disabled="disabled"<?php endif;?>
                    class="checkbox"
                    id="giftcard_use_config_lifetime"
                    name="<?= /* @escapeNotVerified */ $block->getFieldPrefix() ?>[use_config_lifetime]"
                    value="1"
                    <?= /* @escapeNotVerified */ $_checked ?>
                    onclick="toggleValueElements(this, this.up('.field')); toggleDefault('lifetime');" />
                <label for="giftcard_use_config_lifetime" class="normal">
                    <?= /* @escapeNotVerified */ __('Use Config Settings') ?>
                </label>
                <script>
require(['prototype'], function(){

toggleValueElements($('giftcard_use_config_lifetime'), $('giftcard_use_config_lifetime').up('.field'));

});
</script>
            </div>
        </div>

        <div class="admin__field field">
            <label class="label admin__field-label" for="giftcard_allow_message">
                <span><?= /* @escapeNotVerified */ __('Allow Message') ?></span>
            </label>
            <div class="control">
                <select
                    <?php if ($block->isReadonly()):?>disabled="disabled"<?php endif;?>
                    id="giftcard_allow_message" name="<?= /* @escapeNotVerified */ $block->getFieldPrefix() ?>[allow_message]"
                    class="admin__control-select">
                    <option value="1">
                        <?= /* @escapeNotVerified */ __('Yes') ?>
                    </option>
                    <option value="0"<?php if ($block->getFieldValue('allow_message') == 0): ?> selected="selected"<?php endif; ?>>
                        <?= /* @escapeNotVerified */ __('No') ?>
                    </option>
                </select>
                <input
                    type="hidden"
                    id="giftcard_allow_message_default"
                    value="<?= /* @escapeNotVerified */ $block->getConfigValue('allow_message') ?>" />
            </div>
            <div class="field-service" <?= /* @escapeNotVerified */ $block->getScopeValue('[STORE VIEW]') ?>>
                <?php $_checked = ($block->getFieldValue('use_config_allow_message') || $block->IsNew()) ? 'checked="checked"' : '' ?>
                <input
                    type="hidden"
                    name="<?= /* @escapeNotVerified */ $block->getFieldPrefix() ?>[use_config_allow_message]"
                    value="0">
                <input
                    type="checkbox"
                    <?php if ($block->isReadonly()):?>disabled="disabled"<?php endif;?>
                    class="checkbox"
                    id="giftcard_use_config_allow_message"
                    name="<?= /* @escapeNotVerified */ $block->getFieldPrefix() ?>[use_config_allow_message]"
                    value="1"
                    <?= /* @escapeNotVerified */ $_checked ?>
                    onclick="toggleValueElements(this, this.up('.field')); toggleDefault('allow_message');" />
                <label for="giftcard_use_config_allow_message" class="normal">
                    <?= /* @escapeNotVerified */ __('Use Config Settings') ?>
                </label>
                <script>
require(['prototype'], function(){
toggleValueElements($('giftcard_use_config_allow_message'), $('giftcard_use_config_allow_message').up('.field'));
});
</script>
            </div>
        </div>

        <div class="admin__field field">
            <label class="label admin__field-label" for="giftcard_email_template">
                <span><?= /* @escapeNotVerified */ __('Email Template') ?></span>
            </label>
            <div class="control">
                <select
                    <?php if ($block->isReadonly()):?>disabled="disabled"<?php endif;?>
                    id="giftcard_email_template"
                    name="<?= /* @escapeNotVerified */ $block->getFieldPrefix() ?>[email_template]"
                    class="admin__control-select">

                    <?php foreach ($block->getEmailTemplates() as $_value => $_label): ?>
                    <?php $_selected = ($block->getFieldValue('email_template') == $_value ? 'selected="selected"' : ''); ?>
                    <option value="<?= /* @escapeNotVerified */ $_value ?>" <?= /* @escapeNotVerified */ $_selected ?>><?= /* @escapeNotVerified */ $_label ?></option>
                    <?php endforeach; ?>
                </select>
                <input
                    type="hidden"
                    id="giftcard_email_template_default"
                    value="<?= /* @escapeNotVerified */ $block->getConfigValue('email_template') ?>" />
            </div>
            <div class="field-service" <?= /* @escapeNotVerified */ $block->getScopeValue('[STORE VIEW]') ?>>
                <?php $_checked = ($block->getFieldValue('use_config_email_template') || $block->IsNew()) ? 'checked="checked"' : '' ?>
                <input
                    type="hidden"
                    name="<?= /* @escapeNotVerified */ $block->getFieldPrefix() ?>[use_config_email_template]"
                    value="0">
                <input
                    type="checkbox" <?php if ($block->isReadonly()):?>
                    disabled="disabled"<?php endif;?>
                    class="checkbox"
                    id="giftcard_use_config_email_template"
                    name="<?= /* @escapeNotVerified */ $block->getFieldPrefix() ?>[use_config_email_template]"
                    value="1" <?= /* @escapeNotVerified */ $_checked ?>
                    onclick="toggleValueElements(this, this.up('.field')); toggleDefault('email_template');"/>
                <label for="giftcard_use_config_email_template" class="normal">
                    <?= /* @escapeNotVerified */ __('Use Config Settings') ?>
                </label>
                <script>
require(['prototype'], function(){
toggleValueElements($('giftcard_use_config_email_template'), $('giftcard_use_config_email_template').up('.field'));
});
</script>
            </div>
        </div>
    </fieldset>
</div>

<script>
require([
    'jquery',
    'Magento_Catalog/js/product/weight-handler'
], function (jQuery, weightHandle) {

    //<![CDATA[
jQuery(function($){
    window.toggleDefault = function (field)
    {
        var defaultValue = $('#giftcard_' + field + '_default').val(),
            $checkbox = $('#giftcard_use_config_' + field);
        if ($checkbox.is(':checked')) {
            $('#giftcard_' + field).val(defaultValue);
        }
    };

    var toggleOpenAmount = function () {
        $('#open_amount_min,#open_amount_max').prop('disabled', !$('#allow_open_amount').is(':checked'));
    };

    toggleDefault('email_template');
    toggleDefault('is_redeemable');
    toggleDefault('lifetime');
    toggleDefault('allow_message');

    $('#allow_open_amount').on('click', toggleOpenAmount);

    if ($('#allow_open_amount').prop('disabled')) {
        $('#open_amount_min,#open_amount_max').prop('disabled', true);
    } else {
        toggleOpenAmount();
    }

    /**
     * Adding event on card type select box of product to set weight to required or not
     */
    $('[data-tab-panel=product-details]').on('move.tabs', function () {
        $('#giftcard_type').on('change', function () {
            var $weight = $('#weight');
            var isVirtual = $(this).val() == '0';
            if ($weight.length) {
                $weight.prop('disabled', isVirtual);
            }
            $.each($('.hidden-for-virtual'), function () {
                $(this).closest('.field').toggle(!isVirtual);
            });
        }).trigger('change');

        weightHandle.hideWeightSwitcher();
    });
});
    //]]>

});
</script>
