<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
    $item = $block->getItem();
    $wishlists = $block->getWishlists();
?>
<?php if ($block->isMultipleEnabled() && (count($wishlists) || $block->canCreateWishlists($wishlists))): ?>
    <div class="split button"
         data-wishlist-copy='{"copySelectedUrl":"<?= /* @escapeNotVerified */ $block->getCopySelectedUrl() ?>", "copyItemUrl":"<?= /* @escapeNotVerified */ $block->getCopyItemUrl() ?>"}'>
        <div class="wishlist-dropdown addto-wishlist">
            <span class="action toggle change"
                  data-mage-init='{"dropdown":{}}'
                  data-toggle="dropdown"
                  data-trigger-keypress-button="true">
                <span><?= /* @escapeNotVerified */ __('Add to:') ?></span>
            </span>
            <ul class="items dropdown" data-target="dropdown">
                <?php foreach ($wishlists as $wishlist): ?>
                    <li class="item">
                        <span role="button"
                              tabindex="0"
                              data-action-keypress="true"
                              data-wishlist-copy-item='{"itemId":"<?= /* @escapeNotVerified */ $item->getId() ?>", "wishlistId":"<?= /* @escapeNotVerified */ $wishlist->getId() ?>"}'>
                            <?= $block->escapeHtml($wishlist->getName()) ?>
                        </span>
                    </li>
                <?php endforeach;?>
                <?php if ($block->canCreateWishlists($wishlists)): ?>
                    <li class="item">
                        <span role="button"
                              tabindex="0"
                              class="action new"
                              data-action-keypress="true"
                              data-wishlist-copy-item='{"itemId":"<?= /* @escapeNotVerified */ $item->getId() ?>", "new":true}'>
                            <span><?= /* @escapeNotVerified */ __('Create New Wish List') ?></span>
                        </span>
                    </li>
                <?php endif;?>
            </ul>
        </div>
    </div>
<?php else: ?>
    <a href="#"
       class="action towishlist"
       data-post='<?= /* @escapeNotVerified */ $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($item) ?>'
       data-action="add-to-wishlist"
       role="button"
    >
        <span><?= /* @escapeNotVerified */ __('Wishlist') ?></span>
    </a>
<?php endif; ?>
