<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Backend\Block\Widget\Grid\Serializer $block */

// @todo remove this template after MAGETWO-48080

$_id = 'id_' . md5(microtime());
$formId = $block->getFormId()
?>
<?php if (!empty($formId)) :?>
    <script>
        require([
            'prototype',
            'mage/adminhtml/grid'
        ], function(){
            Event.observe(window, "load", function(){
                var serializeInput  = document.createElement('input');
                serializeInput.type = 'hidden';
                serializeInput.name = '<?= $block->escapeJs($block->getInputElementName()) ?>';
                serializeInput.id   = '<?= /* @noEscape */ $_id ?>';
                try {
                    document.getElementById('<?= $block->escapeJs($formId) ?>').appendChild(serializeInput);
                    new serializerController('<?= /* @noEscape */ $_id ?>', <?= /* @noEscape */ $block->getDataAsJSON() ?>, <?= /* @noEscape */ $block->getColumnInputNames(true) ?>, <?= $block->escapeJs($block->getGridBlock()->getJsObjectName()) ?>, '<?= $block->escapeJs($block->getReloadParamName()) ?>');
                } catch(e) {
                    //Error add serializer
                }
            });
        });
    </script>
<?php else :?>
    <input type="hidden" data-form-part="sales_rule_form" name="<?= $block->escapeHtmlAttr($block->getInputElementName()) ?>"  value="" id="<?= /* @noEscape */ $_id ?>" />
    <script>
        require([
            'mage/adminhtml/grid'
        ], function(){
            new serializerController('<?= /* @noEscape */ $_id ?>', <?= /* @noEscape */ $block->getDataAsJSON() ?>, <?= /* @noEscape */ $block->getColumnInputNames(true) ?>, <?= $block->escapeJs($block->getGridBlock()->getJsObjectName()) ?>, '<?= $block->escapeJs($block->getReloadParamName()) ?>');
        });
    </script>
<?php endif; ?>
