<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<h2 class="subtitle">
    <?= $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
</h2>

<form action="<?= /* @escapeNotVerified */ $block->getAddActionUrl() ?>"
      method="post"
      id="form-validate"
      class="form validation form-giftregistry-create"
      data-hasrequired="<?= /* @escapeNotVerified */ __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= /* @escapeNotVerified */ __('General Information') ?></span></legend>

        <div class="field type required">
            <label for="type_id" class="label"><span><?= /* @escapeNotVerified */ __('Gift Registry Type') ?></span></label>
            <div class="control">
                <select data-validate="{required:true}" name="type_id" id="type_id">
                    <option value=""><?= /* @escapeNotVerified */ __('Please select a gift registry type.') ?></option>
                    <?php foreach ($block->getTypeList() as $type):?>
                        <option value="<?= /* @escapeNotVerified */ $type['value'] ?>"><?= /* @escapeNotVerified */ $type['label'] ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" id="submit.next" title="<?= /* @escapeNotVerified */ __('Next') ?>" class="action primary next">
                <span><?= /* @escapeNotVerified */ __('Next') ?></span>
            </button>
        </div>
        <div class="secondary">
            <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="action back">
                <span><?= /* @escapeNotVerified */ __('Back') ?></span>
            </a>
        </div>
    </div>
</form>
