<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>

<form action="<?= /* @escapeNotVerified */ $block->getUrl('*/*/editPost') ?>"
      method="post"
      id="form-validate"
      class="form form-giftregistry-edit validation"
      data-hasrequired="<?= /* @escapeNotVerified */ __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <?= $block->getBlockHtml('formkey') ?>
    <?= $block->getChildHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" id="submit.save" title="<?= /* @escapeNotVerified */ __('Save') ?>" class="action primary save">
                <span><?= /* @escapeNotVerified */ __('Save') ?></span>
            </button>
        </div>
        <div class="secondary">
            <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="action back">
                <span><?= /* @escapeNotVerified */ __('Back') ?></span>
            </a>
        </div>
    </div>
</form>
