<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<input type="hidden" name="entity_id" id="entity_id" value="<?= /* @escapeNotVerified */ $block->getEntity()->getEntityId() ?>" />
<input type="hidden" name="type_id" id="type_id" value="<?= /* @escapeNotVerified */ $block->getTypeId() ?>" />

<p class="giftregistry-type">
    <span class="label"><?= /* @escapeNotVerified */ __('Type:') ?></span>
    <strong><?= /* @escapeNotVerified */ $block->getTypeLabel() ?></strong>
</p>

<fieldset class="fieldset">
    <legend class="legend"><span><?= /* @escapeNotVerified */ __('General Information') ?></span></legend>

    <div class="field event required">
        <label for="title" class="label"><span><?= /* @escapeNotVerified */ __('Event') ?></span></label>
        <div class="control">
            <input type="text" name="title" id="title" value="<?= $block->escapeHtml($block->getEntity()->getTitle()) ?>" title="<?= /* @escapeNotVerified */ __('Event') ?>" class="input-text" data-validate="{required:true}" />
        </div>
    </div>
    <div class="field textarea required">
        <label for="message" class="label"><span><?= /* @escapeNotVerified */ __('Message') ?></span></label>
        <div class="control">
            <textarea name="message" id="message" cols="5" rows="3" title="<?= /* @escapeNotVerified */ __('Message') ?>" data-validate="{required:true}" ><?= $block->escapeHtml($block->getEntity()->getMessage()) ?></textarea>
        </div>
    </div>
    <div class="field privacy required">
        <label for="is_public" class="label"><span><?= /* @escapeNotVerified */ __('Privacy Settings') ?></span></label>
        <div class="control">
            <?= $block->getIsPublicHtml() ?>
        </div>
    </div>
    <div class="field status required">
        <label for="select" class="label"><span><?= /* @escapeNotVerified */ __('Status') ?></span></label>
        <div class="control">
            <?= $block->getStatusHtml() ?>
        </div>
    </div>
</fieldset>

<?php
$fieldsets = $block->getGroupedRegistryAttributes();
foreach ($fieldsets as $fieldset => $fields) : ?>
<fieldset class="fieldset">
    <legend class="legend"><span><?= /* @escapeNotVerified */ $block->getGroupLabel($fieldset) ?></span></legend>

    <?php foreach ($fields as $field => $data) : ?>
        <?php $isRequired = $block->isAttributeRequired($data); ?>
        <div class="field<?= ($isRequired ? ' required' : ''); ?><?= /* @escapeNotVerified */ $field == 'event_date' ? ' date' : '' ?>">
            <label for="<?= /* @escapeNotVerified */ $field ?>" class="label"><span><?= /* @escapeNotVerified */ __($data['label']) ?></span></label>
            <div class="control">
                <?= /* @escapeNotVerified */ $block->renderField($data, $field) ?>
            </div>
        </div>
    <?php endforeach; ?>
    <?php foreach ($fields as $field => $data) : ?>
        <?php if ($block->useRegionUpdater($data)) : ?>
        <script type="text/x-magento-init">
        {
            "#<?= /* @escapeNotVerified */ $field ?>": {
                "regionUpdater": {
                    "optionalRegionAllowed": <?= /* @escapeNotVerified */ ($block->getConfig('general/region/display_all') ? 'true' : 'false') ?>,
                    "regionListId": "#<?= /* @escapeNotVerified */ $field ?>_region",
                    "regionInputId": "#<?= /* @escapeNotVerified */ $field ?>_region_text",
                    "isRegionRequired": false,
                    "isZipRequired": false,
                    "isCountryRequired": true,
                    <?php if ($block->getEntity()->getFieldValue($data['id'] . '_region')) : ?>
                    "currentRegion": <?= /* @escapeNotVerified */ $block->getEntity()->getFieldValue($data['id'] . '_region') ?>,
                    <?php endif; ?>
                    "regionJson": <?= /* @escapeNotVerified */ $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>         
                }
            }
        }
        </script>
        <?php endif; ?>
    <?php endforeach; ?>
</fieldset>
<?php endforeach; ?>
