<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<script id="template-registrant" type="text/x-magento-template">
    <input name="registrant[<%- data._index_ %>][person_id]" value="" id="registrant:person_id<%- data._index_ %>" type="hidden" />
    <div class="actions-toolbar">
        <div class="secondary">
            <button type="button" class="action remove" id="btn-remove<%- data._index_ %>">
                <span>
                    <?= /* @escapeNotVerified */ __('Remove') ?>
                </span>
            </button>
        </div>
    </div>
    <fieldset class="fieldset">
        <div class="field firstname required">
            <label for="registrant:firstname<%- data._index_ %>" class="label"><span><?= /* @escapeNotVerified */ __('First Name') ?></span></label>
            <div class="control">
                <input name="registrant[<%- data._index_ %>][firstname]" value="" type="text" class="input-text" data-validate="{required:true}" id="registrant:firstname<%- data._index_ %>" />
            </div>
        </div>
        <div class="field lastname required">
            <label for="registrant:lastname<%- data._index_ %>" class="label"><span><?= /* @escapeNotVerified */ __('Last Name') ?></span></label>
            <div class="control">
                <input name="registrant[<%- data._index_ %>][lastname]" value="" type="text" class="input-text" data-validate="{required:true}" id="registrant:lastname<%- data._index_ %>" />
            </div>
        </div>
        <div class="field email required">
            <label for="registrant:email<%- data._index_ %>" class="label"><span><?= /* @escapeNotVerified */ __('Email') ?></span></label>
            <div class="control">
                <input name="registrant[<%- data._index_ %>][email]" value="" title="<?= /* @escapeNotVerified */ __('Email') ?>" id="registrant:email<%- data._index_ %>" type="email" class="input-text" data-validate="{required:true,'validate-email':true}"  />
            </div>
        </div>

        <?php foreach ($block->getGroupedRegistrantAttributes() as $field => $data) : ?>
        <?php $isRequired = $block->isAttributeRequired($data); ?>
        <?php $isStatic = $block->isAttributeStatic($field); ?>
            <div class="field<?= ($isRequired ? ' required' : '') ?>">
                <label for="registrant:<?php if (!$isStatic):?>custom:<?php endif;?><?= /* @escapeNotVerified */ $field ?><%- data._index_ %>" class="label"><span><?= /* @escapeNotVerified */ __("%1", $data['label']) ?></span></label>
                <div class="control">
                    <?= /* @escapeNotVerified */ $block->renderField($data, $field, '{{' . $field . '_value}}') ?>
                </div>
            </div>
        <?php endforeach; ?>
    </fieldset>
</script>

<fieldset class="fieldset recipients">
    <legend class="legend"><span><?= /* @escapeNotVerified */ __('Registrant Information') ?></span></legend>
    <br />
    <div id="registrant-container"></div>
    <?php if ($block->getMaxRegistrant()): ?>
        <div id="max-registrant-message" style="display:none;" class="message notice limit" role="alert">
            <span><?= /* @escapeNotVerified */ __('Maximum %1 registrants.', $block->getMaxRegistrant()) ?></span>
        </div>
    <?php endif; ?>
    <div class="actions-toolbar">
        <div class="secondary">
            <?php if ($block->getMaxRegistrant() > 1): ?>
                <button type="button" id="add-registrant-button" class="action add">
                    <span><?= /* @escapeNotVerified */ __('Add Registrant') ?></span>
                </button>
            <?php endif; ?>
        </div>
    </div>
</fieldset>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "giftRegistry": {
                "rowParentElem": "<div></div>",
                "remEventSelector": "button",
                "btnRemoveSelector": ".action.remove",
                "additionalRowClass": "additional",
                "maxRows": "<?= /* @escapeNotVerified */ $block->getMaxRegistrant() ?>",
                "formDataPost": {
                    "formData": <?= /* @escapeNotVerified */ json_encode($block->getRegistrantPresets($block->getEntity()->getId())) ?>
                }
            }
        }
    }
</script>
