<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php if ($block->canDisplayGiftWrappingForItem()): ?>
<div class="gift-options-tooltip-content no-display">
    <?php if ($block->getDesign()): ?>
        <div><strong><?= /* @escapeNotVerified */ __('Gift Wrapping Design') ?></strong>:</div>
        <div><?= /* @escapeNotVerified */ $block->getDesign() ?></div>
    <?php endif; ?>
</div>
<?php endif; ?>
