<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if (count($block->getItems()) > 0): ?>
<form action="<?= /* @escapeNotVerified */ $block->getActionUpdateUrl() ?>"
      method="post"
      id="gift-registry-items-form"
      class="form giftregistry items"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <?= $block->getBlockHtml('formkey') ?>
        <div class="table-wrapper giftregistry">
            <table id="shopping-cart-table" class="data table table-giftregistry-items">
                <caption class="table-caption"><?= /* @escapeNotVerified */ __('Gift Registry') ?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col product"><?= /* @escapeNotVerified */ __('Product') ?></th>
                        <th scope="col" class="col note"><?= /* @escapeNotVerified */ __('Note') ?></th>
                        <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Added On') ?></th>
                        <th scope="col" class="col qty"><?= /* @escapeNotVerified */ __('Qty') ?></th>
                        <th scope="col" class="col fulfilled"><?= /* @escapeNotVerified */ __('Qty Fulfilled') ?></th>
                        <th scope="col" class="col actions"><?= /* @escapeNotVerified */ __('Delete') ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($block->getItems() as $_item): ?>
                    <?= $block->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action primary update">
                    <span><?= /* @escapeNotVerified */ __('Update Gift Registry') ?></span>
                </button>
            </div>
            <div class="secondary">
                <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="action back"><span><?= /* @escapeNotVerified */ __('Back') ?></span></a>
            </div>
        </div>
    </fieldset>
</form>
<?php else: ?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('This gift registry has no items.') ?></span></div>
    <div class="actions-toolbar">
        <div class="secondary">
            <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="action back"><span><?= /* @escapeNotVerified */ __('Back') ?></span></a>
        </div>
    </div>
<?php endif ?>
