<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php $entityCollection = $block->getEntityCollection(); ?>

<?php if ($entityCollection && count($entityCollection)):?>
    <div class="table-wrapper giftregistry">
        <table id="giftregistry-table" class="data table table-giftregistry">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Gift Registry') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col event"><?= /* @escapeNotVerified */ __('Event') ?></th>
                <th scope="col" class="col create"><?= /* @escapeNotVerified */ __('Created On') ?></th>
                <th scope="col" class="col message"><?= /* @escapeNotVerified */ __('Message') ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($entityCollection as $item): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Event')) ?>" class="col event" title="<?= /* @escapeNotVerified */ $block->getEscapedTitle($item) ?>"><?= /* @escapeNotVerified */ $block->truncateString($block->getEscapedTitle($item), 70) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Created On')) ?>" class="col create"><?= /* @escapeNotVerified */ $block->getFormattedDate($item) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Message')) ?>" class="col message"><?= /* @escapeNotVerified */ $block->getEscapedMessage($item) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Action')) ?>" class="col actions">
                        <a href="<?= /* @escapeNotVerified */ $block->getItemsUrl($item) ?>" class="action manage" title="<?= /* @escapeNotVerified */ __('Manage Items') ?>"><?= /* @escapeNotVerified */ __('Manage Items') ?></a>
                        <a href="<?= /* @escapeNotVerified */ $block->getShareUrl($item) ?>" class="action share" title="<?= /* @escapeNotVerified */ __('Share') ?>"><?= /* @escapeNotVerified */ __('Share') ?></a>
                        <a href="<?= /* @escapeNotVerified */ $block->getEditUrl($item) ?>" class="action edit" title="<?= /* @escapeNotVerified */ __('Edit') ?>"><?= /* @escapeNotVerified */ __('Edit') ?></a>
                        <a href="#"
                           data-post='<?= /* @escapeNotVerified */ $block->getDeleteParams($item) ?>'
                           class="action delete"
                           title="<?= /* @escapeNotVerified */ __('Delete') ?>"
                           data-role="remove-gift-registry"
                            ><?= /* @escapeNotVerified */ __('Delete') ?></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getChildHtml('pager')): ?>
        <div class="toolbar giftregistry-toolbar bottom">
            <?= $block->getChildHtml('pager') ?>
        </div>
    <?php endif;?>
<?php else:?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You haven\'t created a gift registry yet.') ?></span></div>
<?php endif;?>

<div class="actions-toolbar">
    <div class="primary">
        <?php if ($block->canAddNewEntity()):?>
            <a href="<?= $block->escapeUrl($block->getAddUrl()) ?>" class="action primary add">
                <span><?= /* @escapeNotVerified */ __('Add New') ?></span>
            </a>
        <?php endif;?>
    </div>
    <div class="secondary">
        <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="action back"><span><?= /* @escapeNotVerified */ __('Back') ?></span></a>
    </div>
</div>
<script>
    require([
        'mage/dataPost',
        'Magento_Ui/js/modal/confirm',
        'prototype'
    ], function(dataPost, confirm){
//<![CDATA[
        $$("[data-role='remove-gift-registry']").each(function(item){
            Event.observe(item, "click", function (event) {
                var params = JSON.parse(jQuery(event.currentTarget).attr('data-post'));

                event.stopPropagation();
                confirm({
                    content: '<?= /* @escapeNotVerified */ __('Are you sure you want to delete this gift registry?') ?>',
                    actions: {
                        confirm: function () {
                            dataPost().postData(params);
                        }
                    }
                });
            });
        });
//]]>
    });
</script>

