<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 */
/* @var $block \Magento\Rma\Block\Form\Renderer\Image */
?>
<a href="<?= /* @escapeNotVerified */ $block->getImageUrl() ?>" target="_blank" class="product photo">
    <img class="product photo preview" src="<?= /* @escapeNotVerified */ $block->getImageUrl() ?>" title="<?= /* @escapeNotVerified */ __('View Full Size') ?>" alt="<?= /* @escapeNotVerified */ __('View Full Size') ?>">
</a>
