<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>

<section class="admin__page-section customer-information">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('General Information') ?></span>
    </div>
    <div class="admin__page-section-content">
        <table class="admin__page-section-item admin__table-secondary gift-registry-info">
            <tbody>
                <tr>
                    <td><strong><?= /* @escapeNotVerified */ __('Type') ?>:</strong></td>
                    <td><?= /* @escapeNotVerified */ $block->getTypeName() ?></td>
                </tr>
                <tr>
                    <td><strong><?= /* @escapeNotVerified */ __('Event') ?>:</strong></td>
                    <td><?= /* @escapeNotVerified */ $block->getEntityTitle() ?></td>
                </tr>
                <tr>
                    <td><strong><?= /* @escapeNotVerified */ __('Message') ?>:</strong></td>
                    <td><?= /* @escapeNotVerified */ $block->getEntityMessage() ?></td>
                </tr>
                <tr>
                    <td><strong><?= /* @escapeNotVerified */ __('Website') ?>:</strong></td>
                    <td><?= /* @escapeNotVerified */ $block->getWebsiteName() ?></td>
                </tr>
                <tr>
                    <td><strong><?= /* @escapeNotVerified */ __('Owner') ?>:</strong></td>
                    <td><a href="<?= /* @escapeNotVerified */ $block->getOwnerUrl() ?>"><?= /* @escapeNotVerified */ $block->getOwnerName() ?></a></td>
                </tr>
                <tr>
                    <td><strong><?= /* @escapeNotVerified */ __('Created on') ?>:</strong></td>
                    <td><?= /* @escapeNotVerified */ $block->getCreatedAt() ?></td>
                </tr>
                <tr>
                    <td><strong><?= /* @escapeNotVerified */ __('Registrants') ?>:</strong></td>
                    <td><?= /* @escapeNotVerified */ $block->getRegistrants() ?></td>
                </tr>
            </tbody>
        </table>
        <address class="admin__page-section-item gift-registry-address">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @escapeNotVerified */ __('Shipping Address') ?></span>
            </div>
            <?= $block->getShippingAddressHtml() ?>
        </address>
    </div>
</section>

<div class="admin__fieldset">
    <?= $block->getChildHtml('sharing_form') ?>
</div>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Gift Registry Items') ?></span>
    </div>
    <form id="update_form" method="post" action="<?= /* @escapeNotVerified */ $block->getActionUrl() ?>">
        <?= $block->getBlockHtml('formkey') ?>
        <?= $block->getChildHtml('entity_items') ?>
        <div class="grid-actions"><?= $block->getChildHtml('update_button') ?></div>
    </form>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Shopping Cart Items') ?></span>
    </div>
    <?= $block->getChildHtml('cart_items') ?>
</section>
