<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\AdvancedCheckout\Block\Adminhtml\Manage\Items
 */
?>
<?php $canReadPrice = ($block->getCanReadPrice() !== false); ?>
<?php $_items = $block->getItems() ?>
<?php if (empty($_items)): ?>
    <div class="admin__table-wrapper" id="order-items_grid">
        <table class="data admin__table-primary order-tables">
            <thead>
                <tr class="headings">
                    <th class="col-product no-link"><span><?= /* @escapeNotVerified */ __('Product') ?></span></th>
                    <?php if ($canReadPrice) : ?>
                    <th class="col-price no-link"><span><?= /* @escapeNotVerified */ __('Price') ?></span></th>
                    <?php endif; ?>
                    <th class="col-qty no-link"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></th>
                    <?php if ($canReadPrice) : ?>
                    <th class="col-price no-link"><span><?= /* @escapeNotVerified */ __('Subtotal') ?></span></th>
                    <?php endif; ?>
                    <th class="col-price no-link"><span><?= /* @escapeNotVerified */ __('Discount') ?></span></th>
                    <?php if ($canReadPrice) : ?>
                    <th class="col-price no-link"><span><?= /* @escapeNotVerified */ __('Row Subtotal') ?></span></th>
                    <?php endif; ?>
                    <?php if ($block->isAllowedActionColumn()): ?>
                    <th class="col-action no-link"><span><?= /* @escapeNotVerified */ __('Action') ?></span></th>
                    <?php endif; ?>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="empty-text" colspan="100"><?= /* @escapeNotVerified */ __('No ordered items') ?></td>
                </tr>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <div class="admin__table-wrapper" id="order-items_grid">
        <table class="data admin__table-primary order-tables">
            <thead>
                <tr class="headings">
                    <th class="col-product no-link"><span><?= /* @escapeNotVerified */ __('Product') ?></span></th>
                    <?php if ($canReadPrice) : ?>
                    <th class="col-price no-link"><span><?= /* @escapeNotVerified */ __('Price') ?></span></th>
                    <?php endif; ?>
                    <th class="col-qty no-link"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></th>
                    <?php if ($canReadPrice) : ?>
                    <th class="col-price no-link"><span><?= /* @escapeNotVerified */ __('Subtotal') ?></span></th>
                    <?php endif; ?>
                    <th class="col-price no-link"><span><?= /* @escapeNotVerified */ __('Discount') ?></span></th>
                    <?php if ($canReadPrice) : ?>
                    <th class="col-price no-link"><span><?= /* @escapeNotVerified */ __('Row Subtotal') ?></span></th>
                    <?php endif; ?>
                    <?php if ($block->isAllowedActionColumn()): ?>
                    <th class="col-action no-link last"><span><?= /* @escapeNotVerified */ __('Action') ?></span></th>
                    <?php endif; ?>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td class="col-total"><?= /* @escapeNotVerified */ __('Total %1 product(s)', count($_items)) ?></td>
                    <?php if ($canReadPrice) : ?>
                    <td colspan="2" class="col-subtotal"><?= /* @escapeNotVerified */ __('Subtotal:') ?></td>
                    <td class="col-price"><strong><?= /* @escapeNotVerified */ $block->formatPrice($block->getSubtotal()) ?></strong></td>
                    <td class="col-price"><strong><?= /* @escapeNotVerified */ $block->formatPrice($block->getDiscountAmount()) ?></strong></td>
                    <td class="col-price"><strong><?= /* @escapeNotVerified */ $block->formatPrice($block->getSubtotalWithDiscount()) ?></strong></td>
                    <?php if ($block->isAllowedActionColumn()): ?>
                    <td>&nbsp;</td>
                    <?php endif; ?>
                    <?php else : ?>
                    <td>&nbsp;</td>
                    <td class="col-price"><strong><?= /* @escapeNotVerified */ $block->formatPrice($block->getDiscountAmount()) ?></strong></td>
                    <?php if ($block->isAllowedActionColumn()) : ?>
                    <td>&nbsp;</td>
                    <?php endif; ?>
                    <?php endif; ?>
                </tr>
            </tfoot>
            <?php $i=0 ?>
            <?php foreach ($_items as $_item):$i++ ?>
                <tbody class="<?= /* @escapeNotVerified */ ($i%2)?'even':'odd' ?>">
                    <tr>
                        <td class="col-product">
                            <span class="title"><?= $block->escapeHtml($_item->getName()) ?></span>
                            <div class="product-sku-block">
                                <span><?= /* @escapeNotVerified */ __('SKU') ?>:</span>
                                <?= implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($_item->getSku()))) ?>
                            </div>
                            <?php if($_item->getMessage(false)): ?>
                            <?php foreach ($_item->getMessage(false) as $message): ?>
                            <div class="<?php if($_item->getHasError()): ?>error<?php else: ?>notice<?php endif; ?>">
                                <div><?= /* @escapeNotVerified */ $message ?></div>
                            </div>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <div class="product-configure-block"><?= $block->getConfigureButtonHtml($_item) ?></div>
                        </td>
                        <?php if ($canReadPrice) : ?>
                        <td class="col-price">
                            <?= $block->getItemUnitPriceHtml($_item) ?>
                        </td>
                        <?php endif; ?>
                        <td class="col-qty">
                            <input name="item[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                                   class="input-text item-qty admin__control-text"
                                   value="<?= /* @escapeNotVerified */ $_item->getQty() * 1 ?>"
                                   maxlength="12">
                        </td>
                        <?php if ($canReadPrice) : ?>
                        <td class="col-price">
                            <?= $block->getItemRowTotalHtml($_item) ?>
                        </td>
                        <?php endif; ?>
                        <td class="col-price">
                            <?= /* @escapeNotVerified */ $block->formatPrice(-$_item->getDiscountAmount()) ?><br />
                        </td>
                        <?php if ($canReadPrice) : ?>
                        <td class="col-price">
                            <?= $block->getItemRowTotalWithDiscountHtml($_item) ?>
                        </td>
                        <?php endif; ?>
                        <?php if ($block->isAllowedActionColumn()): ?>
                        <td class="col-action">
                            <select name="item[<?= /* @escapeNotVerified */ $_item->getId() ?>][action]" class="admin__control-select">
                                <option value=""><?= /* @escapeNotVerified */ __('Please select') ?></option>
                                <option value="remove"><?= /* @escapeNotVerified */ __('Remove') ?></option>
                                <?php if ($block->isMoveToWishlistAllowed($_item)): ?>
                                    <?php $wishlists = $block->getCustomerWishlists();?>
                                    <?php if (count($wishlists) <= 1):?>
                                        <option value="wishlist"><?= /* @escapeNotVerified */ __('Move to Wish List') ?></option>
                                    <?php else: ?>
                                        <optgroup label="<?= /* @escapeNotVerified */ __('Move to Wish List') ?>">
                                        <?php foreach ($wishlists as $wishlist):?>
                                            <option value="wishlist_<?= /* @escapeNotVerified */ $wishlist->getId() ?>"><?= $block->escapeHtml($wishlist->getName()) ?></option>
                                        <?php endforeach;?>
                                        </optgroup>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </select>
                        </td>
                        <?php endif; ?>
                    </tr>
                </tbody>
            <?php endforeach; ?>
        </table>
    </div>
<?php endif; ?>

<?php $listType = $block->getJsObjectName() ?>
<script>
require([
    "Magento_Ui/js/modal/alert",
    "Magento_Ui/js/modal/confirm",
    "prototype",
    "Magento_Catalog/catalog/product/composite/configure"
], function(alert, confirm){

    <?= /* @escapeNotVerified */ $listType ?>cartControl = {
        reload: function (params) {
            if (!params) {
                params = {};
            }
            <?= /* @escapeNotVerified */ $listType ?>.reloadParams = params;
            <?= /* @escapeNotVerified */ $listType ?>.reload();
            <?= /* @escapeNotVerified */ $listType ?>.reloadParams = {};
        },

        configureItem: function (itemId) {
            productConfigure.setOnLoadIFrameCallback('<?= /* @escapeNotVerified */ $listType ?>', this.cbOnLoadIframe.bind(this));
            productConfigure.showItemConfiguration('<?= /* @escapeNotVerified */ $listType ?>', itemId);
            return false;
        },

        cbOnLoadIframe: function (response) {
            if (!response.ok) {
                return;
            }
            this.reload();
        },

        removeItem: function (itemId) {
            var self = this;

            if (!itemId) {
                alert({
                    content: '<?= $block->escapeJs(__('No item specified.')) ?>'
                });

                return false;
            }

            confirm({
                content: '<?= $block->escapeJs(__('Are you sure you want to remove this item?')) ?>',
                actions: {
                    confirm: function() {
                        self.reload({'delete':itemId});

                        return false;
                    }
                }
            });
        }
    };

<?php
$params = array(
    'customer'  => $block->getCustomer()->getId(),
    'store'     => $block->getStore()->getId()
);
?>
    function funcAddItemsListType() {
        productConfigure.addListType('<?= /* @escapeNotVerified */ $listType ?>', {
            urlFetch:  '<?= /* @escapeNotVerified */ $block->getUrl('checkout/index/configureQuoteItems', $params) ?>',
            urlSubmit: ''
        });
    }
    if (typeof(productConfigure) != 'undefined') {
        funcAddItemsListType()
    } else {
        Event.observe(window, 'load', function(){
            setTimeout(funcAddItemsListType, 10);
        })
    }
    
});
</script>
