<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
quoteBaseGrandTotal = <?= (float)$block->getQuote()->getBaseGrandTotal() ?>;
var isGiftCardApplied = <?php if ($block->isFullyPaidAfterApplication()): ?>true<?php else: ?>false<?php endif; ?>;
var epsilon = 0.0001;
function enablePaymentMethods(free) {
    Payment.prototype.init = function () {
        var elements = Form.getElements(this.form);
        var methodName = '';
        for (var i=0; i < elements.length; i++) {
            if (elements[i].name == 'payment[method]'
                || elements[i].name == 'payment[use_customer_balance]'
                || elements[i].name == 'payment[use_reward_points]'
            ) {
                methodName = elements[i].value;
                if ((free && methodName == 'free') || (!free && methodName != 'free')) {
                    $((elements[i]).parentNode).show();
                    if ($('p_method_' + (methodName)) && $('p_method_' + (methodName)).checked) {
                        payment.switchMethod(methodName);
                    }
                    if (free) {
                        elements[i].checked = true;
                        this.switchMethod('free');
                    }
                } else {
                    $((elements[i]).parentNode).hide();
                }
            } else {
                if ($('p_method_' + methodName) && $('p_method_' + methodName).checked) {
                    elements[i].disabled = false;
                } else {
                    elements[i].disabled = true;
                }
            }
        }
    };
}
if (quoteBaseGrandTotal < epsilon && isGiftCardApplied) {
    enablePaymentMethods(true);
} else if (quoteBaseGrandTotal >= epsilon) {
    enablePaymentMethods(false);
}
