<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script>
require([
    'prototype',
    'Magento_Rma/rma'
], function(){

    rma.setLoadAttributesUrl('<?= /* @escapeNotVerified */ $block->getLoadAttributesUrl() ?>');
    rma.setLoadBundleUrl('<?= /* @escapeNotVerified */ $block->getLoadBundleUrl() ?>');
    rma.setLoadOrderId('<?= /* @escapeNotVerified */ $block->getLoadOrderId() ?>');
    $$('a[class="product_to_add"]').each(function(obj) {
        obj.observe('click', rma.showBundleItems.bind(rma));
    });

    $('edit_form').insert({
        bottom: new Element('div', {id: 'details_container'})
    });

});
</script>
