<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<select id="<?= /* @escapeNotVerified */ $block->getSelectRegionId() ?>" name="<?= /* @escapeNotVerified */ $block->getSelectRegionName() ?>" title="<?= /* @escapeNotVerified */ __('State/Province') ?>" class="<?= /* @escapeNotVerified */ $block->getSelectRegionClass() ?>" <?= /* @escapeNotVerified */ $block->getSelectRegionParams() ?>>
    <option value=""><?= /* @escapeNotVerified */ $block->getSelectRegionDefault() ?></option>
</select>
