<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<input type="text" class="input-text <?= /* @escapeNotVerified */ $block->getInputClass() ?> " name="<?= /* @escapeNotVerified */ $block->getInputName() ?>" id="<?= /* @escapeNotVerified */ $block->getInputId() ?>" value="<?= /* @escapeNotVerified */ $block->getInputValue() ?>"  <?= /* @escapeNotVerified */ $block->getInputParams() ?> />
