<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/* @var $block \Magento\VisualMerchandiser\Block\Adminhtml\Category\AddProduct */
// @codingStandardsIgnoreFile
?>
<div data-role="catalog_category_add_product_content" class="admin__old" style="display:none">
    <?= $block->getChildHtml('catalog_category_add_product_tabs') ?>
    <div id="catalog_category_add_product_tabs_content" class="catalog-category-add-product-tabs-content"></div>
</div>
