<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\GiftWrapping\Block\Product\Info */
?>
<?php if ($block->getGiftWrappingInfo()) : ?>
    <dl class="gift-wrapping">
        <dt class="title"><?= /* @escapeNotVerified */ __('Gift Wrapping') ?></dt>
        <dd class="content">
            <?php if ($block->getGiftWrappingInfo()->getImageUrl()): ?>
            <img src="<?= /* @escapeNotVerified */ $block->getGiftWrappingInfo()->getImageUrl() ?>"
                 alt="<?= $block->escapeHtml($block->getGiftWrappingInfo()->getDesign()) ?>"
                title="<?= $block->escapeHtml($block->getGiftWrappingInfo()->getDesign()) ?>" />
            <?php endif ?>
            <?= $block->escapeHtml($block->getGiftWrappingInfo()->getDesign()) ?>
        </dd>
    </dl>
<?php endif; ?>
