<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php $_product = $block->getProduct() ?>
<?php if ($_product->isSaleable() && $block->hasOptions()):?>
<div class="bundle-actions giftregisty">
    <button id="bundle-slide" class="action primary customize" type="button"><span><?= /* @escapeNotVerified */ __('Customize and Add to Gift Registry') ?></span></button>
</div>
<?php endif;?>
