<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Magento\CustomerCustomAttributes\Block\Adminhtml\Form\Renderer\Fieldset\Element
 */
?>

<?php
$element = $block->getElement();
$note = $element->getNote() ? '<div class="note">' . $element->getNote() . '</div>' : '';
$elementBeforeLabel = $element->getExtType() == 'checkbox' || $element->getExtType() == 'radio';
$addOn = $element->getBeforeElementHtml() || $element->getAfterElementHtml();
$fieldId = ($element->getHtmlId()) ? ' id="attribute-' . $element->getHtmlId() . '-container"' : '';
$fieldClass = "field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ($addOn) ? ' with-addon' : '';
$fieldClass .= ($element->getRequired()) ? ' required' : '';
$fieldClass .= ($note) ? ' with-note' : '';

$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
    . $block->getUiId('form-field', $element->getId());
?>

<?php $block->checkFieldDisable() ?>
<?php
$elementToggleCode = $element->getToggleCode() ? $element->getToggleCode()
    : 'toggleValueElements(this, this.parentNode.parentNode.parentNode)';
?>
<?php if (!$element->getNoDisplay()): ?>
<?php if ($element->getType() == 'hidden'): ?>
    <?= $element->getElementHtml() ?>
    <?php else: ?>
    <div<?= /* @escapeNotVerified */ $fieldAttributes ?>>
        <?php if ($elementBeforeLabel): ?>
        <?= $element->getElementHtml() ?>
            <?= $element->getLabelHtml('', $block->getScopeLabel()) ?>
        <?= /* @escapeNotVerified */ $note ?>
        <?php else: ?>
            <?= $element->getLabelHtml('', $block->getScopeLabel()) ?>
        <div class="control">
            <?= /* @escapeNotVerified */ ($addOn) ? '<div class="addon">' . $element->getElementHtml() . '</div>' : $element->getElementHtml() ?>
            <?= /* @escapeNotVerified */ $note ?>
        </div>
        <?php endif; ?>
        <div class="field-service">
            <?php if ($block->canDisplayUseDefault()): ?>
            <label for="<?= $element->getHtmlId() ?>_default" class="choice use-default">
                <input <?php if ($element->getReadonly()):?> disabled="disabled"<?php endif; ?>
                                                            type="checkbox"
                                                            name="use_default[]"
                                                            class="use-default-control"
                                                            id="<?= $element->getHtmlId() ?>_default"
                    <?php if ($block->usedDefault()): ?> checked="checked"<?php endif; ?>
                                                            onclick="<?= /* @escapeNotVerified */ $elementToggleCode ?>"
                                                            value="<?= /* @escapeNotVerified */ $element->getName() ?>"/>
                <span class="use-default-label"><?= /* @escapeNotVerified */ __('Use Default Value') ?></span>
            </label>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>
<?php endif; ?>
