<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Rma\Block\Adminhtml\Rma\Edit\Tab\Items */ ?>

<div class="admin__page-section-item">
    <div class="admin__page-section-item-title">
        <span class="title <?= ($block->getHeaderCssClass()) ? $block->getHeaderCssClass() . ' icon-head' : '' ?>"><?= /* @escapeNotVerified */ $block->getHeaderText() ?></span>
    </div>
    <div class="admin__page-section-content rma-items">
        <?= $block->getChildHtml('', true) ?>
    </div>
</div>
