<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Rma\Block\Adminhtml\Rma\Edit\Tab\General\Shippingmethod
 */

?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Shipping Method') ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php if ($block->getShipment()->getCarrierTitle()): ?>
            <p>
                <strong><?= $block->escapeHtml($block->getShipment()->getCarrierTitle()) ?></strong>
                <?= $block->escapeHtml($block->getShipment()->getMethodTitle()) ?> - <strong class="price"><?= /* @escapeNotVerified */ $block->getShippingPrice($block->getShipment()->getPrice()) ?></strong>
            </p>
        <?php endif; ?>
        <p>
            <?php if ($block->getIsPsl() == \Magento\Rma\Block\Adminhtml\Rma\Edit\Tab\General\Shippingmethod::PSL_ALLOWED): ?>
                <button class="action- save" type="button" id="get-shipping-method-and-rates"><span><?= /* @escapeNotVerified */ __('Create Shipping Label') ?></span></button>
            <?php elseif ($block->getIsPsl() == \Magento\Rma\Block\Adminhtml\Rma\Edit\Tab\General\Shippingmethod::PSL_DISABLED): ?>
                <button class="action- save disabled" type="button" title="<?= /* @escapeNotVerified */ __('Enabled when authorized items require a new shipment.') ?>"><span><?= /* @escapeNotVerified */ __('Create Shipping Label') ?></span></button>
            <?php endif; ?>
            <?php if ($block->getShipment()->getShippingLabel()): ?>
                <?= /* @escapeNotVerified */ $block->getPrintLabelButton() ?>
            <?php endif ?>
            <?php if ($block->getShipment()->getPackages()): ?>
                <?= /* @escapeNotVerified */ $block->getShowPackagesButton() ?>
            <?php endif ?>
        </p>
        <div id="get-psl"></div>
        <?= $block->getChildHtml('magento_rma_shipment_tracking') ?>
    </div>
</div>

<?php include ($block->getTemplateFile('Magento_Shipping::order/packaging/packed.phtml')) ?>
