<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $entityValues = $block->getEntityValues() ?>

<?php if ($block->getEnabled() && count($entityValues)): ?>
<form action="<?= /* @escapeNotVerified */ $block->getAddUrl() ?>"
      method="post"
      id="add-cart-items-to-gift-registry"
      class="form giftregistry"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field giftregistry">
            <div class="control">
                <select id="giftregistry_entity" name="entity" title="<?= /* @escapeNotVerified */ __('Gift Registry') ?>" data-validate="{required:true}">
                    <?php foreach ($entityValues as $_entity):?>
                        <option value="<?= /* @escapeNotVerified */ $_entity->getValue() ?>" title="<?= /* @escapeNotVerified */ $_entity->getTitle() ?>"><?= $block->escapeHtml($block->truncateString($_entity->getTitle(), 40)) ?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>
        <button type="submit" class="action primary add">
            <span><?= /* @escapeNotVerified */ __('Add All To Gift Registry') ?></span>
        </button>
    </fieldset>
</form>
<?php endif; ?>
