<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Rma\Block\Adminhtml\Rma\Create\Order */ ?>
<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <span class="title <?= ($block->getHeaderCssClass()) ? $block->getHeaderCssClass() . ' icon-head' : '' ?>"><?= /* @escapeNotVerified */ $block->getHeaderText() ?></span>
    </div>
    <?= $block->getChildHtml('', true) ?>
</div>
