<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Permissions tab template
 *
 * @see \Magento\CatalogPermissions\Block\Adminhtml\Catalog\Category\Tab\Permissions
 */
?>
<div class="entry-edit form-inline permissions-custom-options" id="category_permissions_<?= /* @escapeNotVerified */ $block->getCategoryId() ?>">
    <div class="messages">
        <div class="message notice">
            <div><?= /* @escapeNotVerified */ __('Permissions do not depend on store views.') ?></div>
        </div>
    </div>
    <div class="box items"></div>
    <div class="actions"><?= $block->getAddButtonHtml() ?></div>
</div>

<script>
require(['Magento_CatalogPermissions/category_edit'], function(){

//<![CDATA[
window.categoryPermissionsTab = new Enterprise.CatalogPermissions.CategoryTab('category_permissions_<?= /* @escapeNotVerified */ $block->getCategoryId() ?>', <?= /* @escapeNotVerified */ $block->getConfigJson() ?>);
//]]>

});
</script>
