<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magento\GiftCardAccount\Block\Adminhtml\Sales\Order\Creditmemo\Controls $block
 */
$source = $block->getSource();
$block->setPriceDataObject($source);
?>

<?php if ((float) $source->getGiftCardsAmount()): ?>
    <tr>
        <td class="label">
            <p><?= $block->escapeHtml(__('Gift Cards')); ?></p>
            <?php if ($block->getGiftcardData()->isRefundToStoreCredit($source)):?>
                <p><small><?= $block->escapeHtml(__('Amount can be returned to Store Credit.'));?></small></p>
            <?php endif;?>
        </td>
        <td>
            <?= /* @noEscape */ $block->displayPrices(-$source->getBaseGiftCardsAmount(), -$source->getGiftCardsAmount()); ?>
        </td>
    </tr>
<?php endif; ?>
