<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/* @var $block \Magento\CustomAttributeManagement\Block\Form\Renderer\Boolean */
?>
<?php
$fieldCssClass = 'field field-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
?>
<div class="<?= /* @escapeNotVerified */ $fieldCssClass ?>">
    <label class="label" for="<?= $block->getHtmlId() ?>"><span><?= /* @escapeNotVerified */ $block->getLabel() ?></span></label>
    <div class="control">
        <select id="items:<?= $block->getHtmlId() ?><%- data._index_ %>" name="items[<%- data._index_ %>][<?= /* @escapeNotVerified */ $block->getFieldName() ?>]"<?php if ($block->getHtmlClass()):?> class="select <?= $block->getHtmlClass() ?>"<?php endif;?>>
            <?php foreach ($block->getOptions() as $option):?>
                <option value="<?= /* @escapeNotVerified */ $option['value'] ?>"<?php if ($option['value'] == $block->getValue()):?> selected="selected"<?php endif;?>><?= $block->escapeHtml($option['label']) ?></option>
            <?php endforeach;?>
        </select>
        <?php if ($_message = $block->getAdditionalDescription()) : ?>
            <div class="note"><?= /* @escapeNotVerified */ $_message ?></div>
        <?php endif; ?>
    </div>
</div>
