<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 */
/* @var $block \Magento\Rma\Block\Form\Renderer\Image */
?>
<div class="field <?= $block->getHtmlId() ?><%- data._index_ %><?php if ($block->isRequired()) { echo ' required'; } ?>">
    <label for="items:<?= $block->getHtmlId() ?><%- data._index_ %>" class="label"><span><?= /* @escapeNotVerified */ $block->getLabel() ?></span></label>
    <div class="control">
        <input type="file" id="items:<?= $block->getHtmlId() ?><%- data._index_ %>" name="<?= /* @escapeNotVerified */ $block->getFieldName() ?>_<%- data._index_ %>" value="" class="input-file">
        <input type="hidden" id="items:<?= $block->getHtmlId() ?><%- data._index_ %>_value" name="<?= /* @escapeNotVerified */ $block->getFieldName() ?>_<%- data._index_ %>_value" value="<?= /* @escapeNotVerified */ $block->getEscapedValue() ?>" <?php if ($block->isRequired()): ?>data-validate="{required:true}" <?php endif;?>>
    </div>
</div>
