<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 */
/* @var $block \Magento\CustomAttributeManagement\Block\Form\Renderer\Textarea */
?>
<div class="field <?= $block->getHtmlId() ?><%- data._index_ %><?php if ($block->isRequired()) { echo ' required'; }?>">
    <label for="items:<?= $block->getHtmlId() ?><%- data._index_ %>" class="label"><span><?= /* @escapeNotVerified */ $block->getLabel() ?></span></label>
    <div class="control">
        <textarea id="items:<?= $block->getHtmlId() ?><%- data._index_ %>" name="items[<%- data._index_ %>][<?= /* @escapeNotVerified */ $block->getFieldName() ?>]" rows="5" cols="25" class="input-text <?= $block->getHtmlClass();?>"><?= /* @escapeNotVerified */ $block->getEscapedValue() ?></textarea>
    </div>
</div>
