<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\AdvancedCheckout\Block\Adminhtml\Sku\Errors\Grid\Description */ ?>
<?php $_item = $block->getItem() ?>
<?php $_product = $block->getItem()->getProduct() ?>
<?php $_sku = $block->escapeHtml($_item->getSku()) ?>
<div id="<?= /* @escapeNotVerified */ 'sku_' . $_sku ?>" class="sku-failed-item">
    <?php if ($_product->getName()): ?>
        <p><strong><?= $block->escapeHtml($_product->getName()) ?></strong></p>
    <?php endif ?>

    <p><strong><?= /* @escapeNotVerified */ __('SKU: ') ?></strong> <?= /* @escapeNotVerified */ $_sku ?></p>

    <div class="messages">
        <div class="message message-notice">
            <?= /* @escapeNotVerified */ $block->getErrorMessage($_item) ?>
        </div>
    </div>

    <div class="sku-configure-button">
        <?= $block->getConfigureButtonHtml() ?>
    </div>

    <?php if ($_item->getQtyMaxAllowed()): ?>
        <?= /* @escapeNotVerified */ __('Only <span id="%1_max_allowed">%2</span> in stock', $_sku, $_item->getQtyMaxAllowed()) ?>
    <?php endif ?>
    <input type="hidden" name="sku" value="<?= /* @escapeNotVerified */ $_sku ?>"/>
    <input type="checkbox" name="<?= /* @escapeNotVerified */ $block->getSourceId() ?>" value="<?= /* @escapeNotVerified */ $_sku ?>" checked="checked" style="display:none"/>
</div>
