<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\GiftWrapping\Block\Adminhtml\Order\View\Info */
?>
<?php if ($block->canDisplayGiftWrapping()): ?>
<div id="wrapping-order-container" class="order-gift-wrapping">
    <legend class="admin__legend">
        <span><?= /* @escapeNotVerified */ __('Gift Wrapping for the Entire Order') ?></span>
    </legend><br />

    <?php if ($block->getOrderInfo()->getDesign()): ?>
    <div class="gift-wrapping-form">
        <div class="gift-wrapping-design">
            <?php if ($block->getOrderInfo()->getPath()): ?>
                <img id="image-box"
                     class="image-box"
                     alt="<?= $block->escapeHtml($block->getOrderInfo()->getDesign()) ?>"
                     src="<?= /* @escapeNotVerified */ $block->getOrderInfo()->getPath() ?>"/>
            <?php endif; ?>
            <?= /* @escapeNotVerified */ __('Gift Wrapping Design') ?>: <span><?= $block->escapeHtml($block->getOrderInfo()->getDesign()) ?></span>
            <div id="price-box" class="price-box item-price-box">
                <?php if ($block->getDisplayWrappingBothPrices()): ?>
                <div>
                    <span class="label"><?= /* @escapeNotVerified */ __('Price Excl. Tax') ?>:</span>
                    <span class="price"><?= /* @escapeNotVerified */ $block->getOrderInfo()->getPriceExclTax() ?></span>
                </div>
                <div>
                    <span class="label"><?= /* @escapeNotVerified */ __('Price Incl. Tax') ?>:</span>
                    <span class="price"><?= /* @escapeNotVerified */ $block->getOrderInfo()->getPriceInclTax() ?></span>
                </div>
                <?php else: ?>
                <div>
                    <span class="label"><?= /* @escapeNotVerified */ __('Price') ?>:</span>
                    <span class="price"><?= /* @escapeNotVerified */ $block->getOrderInfo()->getPrice() ?></span>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?php endif; ?>

    <?php if ($block->getGiftReceipt()): ?>
    <div class="gift-options-receipt admin__field admin__field-option">
        <input type="checkbox"
               id="allow-gift-receipt"
               class="admin__control-checkbox"
               disabled="disabled"
               <?php if ($block->getGiftReceipt()): ?> checked="checked"<?php endif; ?>/>
        <label for="allow-gift-receipt" class="admin__field-label">
            <?= /* @escapeNotVerified */ __('Send Gift Receipt') ?>
        </label>
    </div>
    <?php endif; ?>
    <?php if ($block->getPrintedCard()): ?>
    <div class="admin__field admin__field-option">
        <input type="checkbox"
               id="add-printed-card"
               class="admin__control-checkbox"
               disabled="disabled"
            <?php if ($block->getPrintedCard()): ?> checked="checked"<?php endif; ?>/>
        <label for="add-printed-card" class="admin__field-label">
            <?= /* @escapeNotVerified */ __('Add Printed Card') ?>
        </label>
    </div>
    <div id="price-card-box" class="price-box">
    <?php if ($block->getDisplayCardBothPrices()): ?>
        <div>
            <span class="label"><?= /* @escapeNotVerified */ __('Price Excl. Tax') ?>:</span>
            <span class="price"><?= /* @escapeNotVerified */ $block->getCardInfo()->getPriceExclTax() ?></span>
        </div>
        <div>
            <span class="label"><?= /* @escapeNotVerified */ __('Price Incl. Tax') ?>:</span>
            <span class="price"><?= /* @escapeNotVerified */ $block->getCardInfo()->getPriceInclTax() ?></span>
        </div>
    <?php else: ?>
        <div>
            <span class="label"><?= /* @escapeNotVerified */ __('Price') ?>:</span>
            <span class="price"><?= /* @escapeNotVerified */ $block->getCardInfo()->getPrice() ?></span>
        </div>
    <?php endif; ?>
    </div>
    <?php endif; ?>
</div>
<?php endif; ?>
