<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var \Magento\GoogleTagManager\Block\ListJson $block */
$bannerCollection =  $block->getBannerCollection();
$position = $block->getBannerPosition();
?>

<?php if ($bannerCollection != null && $bannerCollection->count()) { ?>
    <script>
        var <?= /* @escapeNotVerified */ $block->getVariableName() ?> =
        <?= /* @escapeNotVerified */ $block->getVariableName() ?> ||
        [];
        <?= /* @escapeNotVerified */ $block->getVariableName() ?>
        = [
    <?php
    foreach ($bannerCollection as $banner) {
        ?>
            {
                'id': '<?= /* @escapeNotVerified */ $banner->getBannerId() ?>',
                'name': '<?= $block->escapeJs($banner->getName()) ?>',
                'creative': '<?= /* @escapeNotVerified */ $banner->getGaCreative() ?>',
                'position': '<?= /* @escapeNotVerified */ $position ?>',
                'activated': '<?= /* @escapeNotVerified */ $banner->getIsGaEnabled() ?>'
            },
        <?php
    }
    ?>
        ];
    </script>
    <?php
}
