<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="grid">
    <?php $randomId = rand(); ?>
    <div class="admin__table-wrapper">
        <table class="data-grid">
            <thead>
            <tr>
                <th class="data-grid-checkbox-cell">
                    <label class="data-grid-checkbox-cell-inner">
                        <input type="checkbox"
                               id="select-items-<?= /* @noEscape */ $randomId ?>"
                               onchange="packaging.checkAllItems(this);"
                               class="checkbox admin__control-checkbox"
                               title="<?= /* @escapeNotVerified */ __('Select All') ?>">
                        <label for="select-items-<?= /* @noEscape */ $randomId ?>"></label>
                    </label>
                </th>
                <th class="data-grid-th"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
                <th class="data-grid-th"><?= /* @escapeNotVerified */ __('Weight') ?></th>
                <th class="data-grid-th" <?= $block->displayCustomsValue() ? '' : 'style="display: none;"' ?>>
                    <?= /* @escapeNotVerified */ __('Customs Value') ?>
                </th>
                <th class="data-grid-th"><?= /* @escapeNotVerified */ __('Qty Ordered') ?></th>
                <th class="data-grid-th"><?= /* @escapeNotVerified */ __('Qty') ?></th>
            </tr>
            </thead>

            <tbody>
            <?php $i=0; ?>
            <?php foreach ($block->getCollection() as $item): ?>
                <tr class="data-grid-controls-row data-row <?= ($i++ % 2 != 0) ? '_odd-row' : ''; ?>">
                    <td class="data-grid-checkbox-cell">
                        <?php $id = $item->getId(); ?>
                        <label class="data-grid-checkbox-cell-inner">
                            <input type="checkbox"
                                   id="select-item-<?= /* @noEscape */ $randomId . '-' . $id ?>"
                                   value="<?= /* @escapeNotVerified */ $id ?>"
                                   class="checkbox admin__control-checkbox">
                            <label for="select-item-<?= /* @noEscape */ $randomId . '-' . $id ?>"></label>
                        </label>
                    </td>
                    <td>
                        <?= /* @escapeNotVerified */ $item->getName() ?>
                    </td>
                    <td data-role="item-weight">
                        <?= /* @escapeNotVerified */ $item->getWeight() ?>
                    </td>
                    <?php
                        if ($block->displayCustomsValue()) {
                            $customsValueDisplay = '';
                            $customsValueValidation = ' validate-zero-or-greater ';
                        } else {
                            $customsValueDisplay = ' style="display: none;" ';
                            $customsValueValidation = '';
                        }
                    ?>
                    <td <?= /* @escapeNotVerified */ $customsValueDisplay ?>>
                        <input type="text" name="customs_value" class="input-text <?= /* @escapeNotVerified */ $customsValueValidation ?>" value="<?= /* @escapeNotVerified */ $block->formatPrice($item->getPrice()) ?>" size="10" onblur="packaging.recalcContainerWeightAndCustomsValue(this);">
                    </td>
                    <td>
                        <?= /* @escapeNotVerified */ $item->getQty() ?>
                    </td>
                    <td>
                        <input type="hidden" name="price" value="<?= /* @escapeNotVerified */ $item->getPrice() ?>">
                        <input type="text" name="qty" value="<?= /* @escapeNotVerified */ $item->getQty()*1 ?>" class="admin__control-text input-text qty qty-decimal">
                        <button type="button" data-action="package-delete-item" class="action-delete" onclick="packaging.deleteItem(this);" style="display:none;">
                            <span><?= /* @escapeNotVerified */ __('Delete') ?></span>
                        </button>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
