<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Rma\Block\Adminhtml\Rma\Edit\Tab\General\Shipping\Information
 */
?>
<div id="checkout-shipping-method-load" class="admin__page-section">
<div class="admin__page-section-title">
    <span class="title"><?= /* @escapeNotVerified */ __('Shipping Information') ?></span>
</div>
<div class="admin__page-section-content">
    <p>
        <strong id="get-shipping-method-carrier-title"></strong>
        <span id="get-shipping-method-method-title"></span>
        <strong class="price" id="get-shipping-method-shipping-price"></strong>
    </p>
    <p>
        <a href="javascript:void(0)" id="get-shipping-method-show-shipping-methods"><?= /* @escapeNotVerified */ __('Change shipping method.') ?></a>
    </p>
</div>
