<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Rma\Block\Adminhtml\Rma\Edit\Tab\General\Shipping\Tracking */ ?>
<div class="admin__control-table-wrapper">
    <table
        id="shipment_tracking_info"
        class="data-table admin__control-table">
        <thead>
            <tr class="headings">
                <th class="col-carrier"><?= /* @escapeNotVerified */ __('Carrier') ?></th>
                <th class="col-title"><?= /* @escapeNotVerified */ __('Title') ?></th>
                <th class="col-number"><?= /* @escapeNotVerified */ __('Number') ?></th>
                <th class="col-delete"><?= /* @escapeNotVerified */ __('Action') ?></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td class="col-carrier">
                    <select name="carrier"
                            class="admin__control-select"
                            onchange="selectCarrier(this)">
                        <option value="custom"><?= /* @escapeNotVerified */ __('Custom Value') ?></option>
                        <?php foreach ($block->getCarriers() as $_code => $_name): ?>
                        <option value="<?= /* @escapeNotVerified */ $_code ?>"><?= $block->escapeHtml($_name) ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td class="col-title">
                    <input
                        id="tracking_title"
                        class="input-text admin__control-text"
                        type="text"
                        name="title"
                        value="" />
                </td>
                <td class="col-number">
                    <input
                        id="tracking_number"
                        class="input-text admin__control-text"
                        type="text"
                        name="number"
                        value="" />
                </td>
                <td class="col-delete">
                    <?= $block->getSaveButtonHtml() ?>
                </td>
            </tr>
        </tfoot>
    <?php if ($_tracks = $block->getAllTracks()): ?>
        <tbody>
        <?php $i = 0; foreach ($_tracks as $_track):$i++ ?>
            <tr class="<?= /* @escapeNotVerified */ ($i%2 == 0) ? 'even' : 'odd' ?>">
                <td class="col-carrier"><?= $block->escapeHtml($block->getCarrierTitle($_track->getCarrierCode())) ?></td>
                <td class="col-title"><?= $block->escapeHtml($_track->getCarrierTitle()) ?></td>
                <td class="col-number">
                    <?php if ($_track->isCustom()): ?>
                        <?= $block->escapeHtml($_track->getTrackNumber()) ?>
                    <?php else: ?>
                    <a href="#" onclick="popWin('<?= /* @escapeNotVerified */ $this->helper('Magento\Rma\Helper\Data')->getTrackingPopupUrlBySalesModel($_track) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')"><?= $block->escapeHtml($_track->getTrackNumber()) ?></a>
                    <div id="shipment_tracking_info_response_<?= /* @escapeNotVerified */ $_track->getId() ?>"></div>
                    <?php endif; ?>
                </td>
                <td class="col-delete"><button type="button" class="action-delete" onclick="deleteTrackingNumber('<?= /* @escapeNotVerified */ $block->getRemoveUrl($_track) ?>'); return false;" title="<?= /* @escapeNotVerified */ __('Delete') ?>"><span><?= /* @escapeNotVerified */ __('Delete') ?></span></button></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    <?php endif; ?>
    </table>
</div>
<script>
require(['prototype'], function(){

//<![CDATA[
selectCarrier = function(elem) {
    var option = elem.options[elem.selectedIndex];
    $('tracking_title').value = option.value && option.value != 'custom' ? option.text : '';
}

deleteTrackingNumber = function(url) {
    if (confirm('<?= /* @escapeNotVerified */ __('Are you sure?') ?>')) {
        submitAndReloadArea($('shipment_tracking_info').parentNode, url)
    }
}
//]]>

});
</script>
