<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\GiftCard\Block\Adminhtml\Catalog\Product\Composite\Fieldset\Giftcard */?>
<?php $_product = $block->getProduct(); ?>
<?php $_id = $_product->getId(); ?>
<?php $_storeId = $_product->getStoreId(); ?>
<?php $_skipSaleableCheck = $this->helper('Magento\Catalog\Helper\Product')->getSkipSaleableCheck(); ?>
<script>
require([
    "Magento_Catalog/catalog/product/composite/configure"
], function(){
    productConfigure.giftcardConfig = {};
});
</script>
<div id="catalog_product_composite_configure_fields_downloadable" class="giftcard <?= $block->getIsLastFieldset() ? 'last-fieldset' : '' ?>">

<?php if (!$_product->isAvailable() && !$_skipSaleableCheck): ?>
    <p class="stock unavailable"><?= /* @escapeNotVerified */ __('Availability:') ?> <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></p>
<?php endif; ?>

    <div class="product options">
    <fieldset class="admin__fieldset">
<?php if (($_product->isSaleable() || $_skipSaleableCheck) && $block->isConfigured($_product)): ?>
    <?php if (!$block->isOpenAmountAvailable($_product) && (count($block->getAmounts($_product)) == 1)): ?>
        <?php $_amount = $block->getAmounts($_product); $_amount = array_shift($_amount); ?>
        <div class="field fixed amount admin__field"> <?php /* ToDo UI: try to remove one word classes */?>
            <label class="label admin__field-label"><span><?= /* @escapeNotVerified */ __('Amount') ?></span></label>
            <div class="control admin__field-control">
                <div class="admin__field-value">
                    <span class="control-value price" id="product-price-<?= /* @escapeNotVerified */ $_id ?><?= /* @escapeNotVerified */ $block->getIdSuffix() ?>">
                    <input type="hidden" value="<?= /* @escapeNotVerified */ $_amount ?>" price="<?= /* @escapeNotVerified */ $_amount ?>" name="giftcard_amount" />
                    <?= /* @escapeNotVerified */ $this->helper('Magento\Framework\Pricing\Helper\Data')->currencyByStore($_amount, $_storeId, true, false) ?>
                </span>
                </div>
            </div>
        </div>

    <?php else: ?>
        <div class="giftcard-amount admin__fieldset">
            <div class="field amount required _required admin__field">
                <?php if ($block->isAmountAvailable($_product)): ?>
                    <label for="giftcard_amount" id="amount_label_select" class="label admin__field-label">
                        <span><?= /* @escapeNotVerified */ __('Amount') ?></span>
                    </label>
                <?php
                    $configValue = $block->getDefaultValue('giftcard_amount');
                ?>
                <div class="control admin__field-control">
                    <select name="giftcard_amount" id="giftcard_amount" class="required-entry select admin__control-select" onchange="productConfigure.giftcardConfig.switchGiftCardInputs.call(this,event||window.event)">
                        <option value=""><?= /* @escapeNotVerified */ __('Choose an Amount...') ?></option>
                        <?php foreach ($block->getAmounts($_product) as $value): ?>
                            <option value="<?= /* @escapeNotVerified */ $value ?>" price="<?= /* @escapeNotVerified */ $this->helper('Magento\Framework\Pricing\Helper\Data')->currencyByStore($value, $_storeId, false) ?>" <?= (($configValue == $value) ? 'selected' : '')?>><?= /* @escapeNotVerified */ $this->helper('Magento\Framework\Pricing\Helper\Data')->currencyByStore($value, $_storeId, true, false) ?></option>
                        <?php endforeach; ?>

                        <?php if ($block->isOpenAmountAvailable($_product)): ?>
                            <option value="custom" <?= (($configValue == 'custom') ? 'selected' : '')?>><?= /* @escapeNotVerified */ __('Other Amount...') ?></option>
                        <?php endif; ?>
                    </select>
                </div>
                <?php endif; ?>
            </div>

            <?php if ($block->isOpenAmountAvailable($_product)): ?>
                <?php if (count($block->getAmounts($_product)) === 0): ?>
                    <input  type="hidden" name="giftcard_amount" value="custom">
                <?php endif; ?>
            <div class="field amount required admin__field" id="giftcard_amount_input_fields">
                <label for="giftcard_amount_input" id="amount_label_input" class="label admin__field-label">
                    <span><?= /* @escapeNotVerified */ __('Amount in %1', $block->getCurrentCurrencyCode($_storeId)) ?></span>
                </label>
                <div id="giftcard_amount_box" class="control admin__field-control">
                    <input type="text" id="giftcard_amount_input" name="custom_giftcard_amount"
                           class="validate-number required-entry input-text admin__control-text giftcard-min-amount giftcard-max-amount"
                           value="<?= $block->escapeHtml($block->getDefaultValue('custom_giftcard_amount')) ?>"
                           price="<?= $block->escapeHtml($block->getDefaultValue('custom_giftcard_amount')) ?>"
                           onblur="this.setAttribute('price', this.value);"/>

                    <?php if ($_product->getOpenAmountMin() || $_product->getOpenAmountMax()): ?>
                        <?php $_min = $this->helper('Magento\Framework\Pricing\Helper\Data')->currencyByStore($_product->getOpenAmountMin(), $_storeId, true, false); ?>
                        <?php $_max = $this->helper('Magento\Framework\Pricing\Helper\Data')->currencyByStore($_product->getOpenAmountMax(), $_storeId, true, false); ?>
                        <div class="admin__field-note">
                            <?php if ($_product->getOpenAmountMax() && $_product->getOpenAmountMin()): ?>
                                <span><?= /* @escapeNotVerified */ __('Minimum') ?><span class="price"><?= /* @escapeNotVerified */ __($_min) ?></span></span>
                                <span><?= /* @escapeNotVerified */ __('Maximum') ?><span class="price"><?= /* @escapeNotVerified */ __($_max) ?></span></span>
                            <?php elseif ($_product->getOpenAmountMin()): ?>
                                <span><?= /* @escapeNotVerified */ __('Minimum') ?><span class="price"><?= /* @escapeNotVerified */ __($_min) ?></span></span>
                            <?php elseif ($_product->getOpenAmountMax()): ?>
                                <span><?= /* @escapeNotVerified */ __('Maximum') ?><span class="price"><?= /* @escapeNotVerified */ __($_max) ?></span></span>
                            <?php endif; ?>
                        </div>
                        <script>
require([
    "Magento_GiftCard/catalog/product/composite/fieldset/validation-rules",
    "Magento_Catalog/catalog/product/composite/configure"
], function(){

//<![CDATA[
    productConfigure.giftcardConfig.minAllowedAmount = <?= /* @escapeNotVerified */ $this->helper('Magento\Framework\Pricing\Helper\Data')->currencyByStore($_product->getOpenAmountMin(), $_storeId, false, false) ?>;
    productConfigure.giftcardConfig.maxAllowedAmount = <?= /* @escapeNotVerified */ $this->helper('Magento\Framework\Pricing\Helper\Data')->currencyByStore($_product->getOpenAmountMax(), $_storeId, false, false) ?>;

    productConfigure.giftcardConfig.parsePrice = function (value) {
        value = value.replace('\'', '').replace(' ', '');
        separatorComa = value.indexOf(',');
        separatorDot  = value.indexOf('.');

        if (separatorComa != -1 && separatorDot != -1) {
            if (separatorComa > separatorDot) {
                value = value.replace('.', '').replace(',', '.');
            } else {
                value = value.replace(',', '');
            }
        } else if (separatorComa != -1) {
            value = value.replace(',', '.');
        }

        return parseFloat(value);
    };
//]]>

});
</script>
                    <?php endif; ?>
                </div>
            </div>
            <?php endif; ?>
        </div>
        <script>
require([
    "prototype",
    "Magento_Catalog/catalog/product/composite/configure"
], function(){

        productConfigure.giftcardConfig.switchGiftCardInputs = function ()
        {
            if (!$('giftcard_amount') || !$('giftcard_amount_input_fields')) {
                return;
            }

            var customAmount = $('giftcard_amount_input');
            var value = $('giftcard_amount').options[$('giftcard_amount').selectedIndex].value;
            if (value == 'custom') {
                $('giftcard_amount_input_fields').show();
                if (customAmount) {
                    customAmount.disabled = false;
                }
            } else {
                $('giftcard_amount_input_fields').hide();
                if (customAmount) {
                    customAmount.disabled = true;
                }
            }
        }

        if ($('giftcard_amount') && $('giftcard_amount_input_fields')) {
            $('giftcard_amount_input_fields').hide();
        }

        productConfigure.giftcardConfig.switchGiftCardInputs();

});
</script>
    <?php endif; ?>
        <?= $block->getChildHtml('product.composite.giftcard.qty') ?>
            <div class="field admin__field sender name required _required">
                <label for="giftcard_sender_name" class="label admin__field-label"><span><?= /* @escapeNotVerified */ __('Sender Name') ?></span></label>
                <div class="control admin__field-control">
                    <input type="text" id="giftcard_sender_name" name="giftcard_sender_name"
                           class="required-entry input-text admin__control-text"
                           value="<?= $block->escapeHtml($block->getDefaultValue('giftcard_sender_name')) ?>"/>
                </div>
            </div>
            <?php if ($block->isEmailAvailable($_product)): ?>
            <div class="field admin__field sender email required _required">
                <label for="giftcard_sender_email" class="label admin__field-label"><span><?= /* @escapeNotVerified */ __('Sender Email') ?></span></label>
                <div class="control admin__field-control">
                    <input type="text" id="giftcard_sender_email" name="giftcard_sender_email"
                           class="validate-email required-entry input-text admin__control-text"
                           value="<?= $block->escapeHtml($block->getDefaultValue('giftcard_sender_email')) ?>"/>
                </div>
            </div>
            <?php endif; ?>
            <div class="field admin__field recipient name required _required">
                <label for="giftcard_recipient_name" class="label admin__field-label"><span><?= /* @escapeNotVerified */ __('Recipient Name') ?></span></label>
                <div class="control admin__field-control">
                    <input type="text" id="giftcard_recipient_name" name="giftcard_recipient_name"
                           class="required-entry input-text admin__control-text"
                           value="<?= $block->escapeHtml($block->getDefaultValue('giftcard_recipient_name')) ?>"/>
                </div>
            </div>
            <?php if ($block->isEmailAvailable($_product)): ?>
            <div class="field admin__field recipient email required _required">
                <label for="giftcard_recipient_email" class="label admin__field-label"><span><?= /* @escapeNotVerified */ __('Recipient Email') ?></span></label>
                <div class="control admin__field-control">
                    <input type="text" id="giftcard_recipient_email" name="giftcard_recipient_email"
                           class="validate-email required-entry input-text admin__control-text"
                           value="<?= $block->escapeHtml($block->getDefaultValue('giftcard_recipient_email')) ?>"/>
                </div>
            </div>
            <?php endif; ?>
        <?php if ($block->isMessageAvailable($_product)): ?>
            <div class="field admin__field text">
                <label for="giftcard_message" class="label admin__field-label"><span><?= /* @escapeNotVerified */ __('Message') ?></span></label>
                <div class="control admin__field-control">
                    <textarea name="giftcard_message" id="giftcard_message"
                              class="input-text giftcard-message-max-length admin__control-textarea" cols="5"
                              rows="3"><?= $block->escapeHtml($block->getDefaultValue('giftcard_message')) ?></textarea>
                    <?php if ($block->getMessageMaxLength()): ?>
                        <script>
require([
    "jquery",
    "mage/validation"
], function(jQuery){

    jQuery.validator.addMethod('giftcard-message-max-length', function(v) {
        return v.length <= <?= /* @escapeNotVerified */ $block->getMessageMaxLength() ?>;
    }, '<?= /* @escapeNotVerified */ __('Maximum length of the message is %1 characters.', $block->getMessageMaxLength()) ?>');

});
</script>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    <?php endif; ?>
    </fieldset>
    </div>
</div>
