<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\GoogleTagManager\Block\ListJson $block */
?>

<div id="checkout-shipping-load">
    <!-- Content loaded dynamically -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_GoogleTagManager/js/actions/checkout": {
                "cart": <?= /* @escapeNotVerified */ $block->getCartContent() ?>
            }
        }
    }
</script>