<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_GoogleTagManager/js/actions/multicheckout": {
                "step": "<?= /* @NoEscape */ $block->getStepName() ?>",
                "cart": <?= /* @NoEscape */  $block->getCartContent() ?>
            }
        }
    }
</script>