<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Invitation\Block\Form */?>
<?= $block->getChildHtml('form_before') ?>

<?php $maxPerSend = $block->getMaxInvitationsPerSend(); ?>
<?php if ($maxPerSend): ?>
    <form id="invitationForm" action="" method="post" class="form form-add-invitations" data-mage-init='{
        "rowBuilder":{
            "rowTemplate":"#add-email-friends-tmpl",
            "rowContainer":"#invitations-options",
            "rowParentElem":"<div></div>",
            "remEventSelector":"button",
            "btnRemoveSelector":".action.remove",
            "maxRows":"<?= /* @escapeNotVerified */ $block->getMaxInvitationsPerSend() ?>",
            "maxRowsMsg":"#max-emails-message",
            "addRowBtn":"#add-email-button",
            "additionalRowClass":"additional"},
        "validation":{}}'
        data-hasrequired="<?= /* @escapeNotVerified */ __('* Required Fields') ?>">

        <input name="form_key" type="hidden" value="<?= $block->escapeHtml($block->getFormKeyValue()) ?>" />

        <fieldset class="fieldset">
            <legend class="legend">
                <span><?= /* @escapeNotVerified */ __('Invite your friends by entering their email addresses') ?></span>
            </legend>
            <br>

            <div id="invitations-options"></div>

            <?php if ($block->isInvitationMessageAllowed()): ?>
                <div id="max-emails-message" style="display: none;" class="message notice limit" role="alert">
                    <span><?= /* @escapeNotVerified */ __('Maximum %1 email addresses allowed.', $block->getMaxInvitationsPerSend()) ?></span>
                </div>
            <?php endif; ?>
            
            <div class="actions-toolbar">
                <div class="secondary">
                    <?php if (1 < $block->getMaxInvitationsPerSend()): ?>
                        <button type="button" id="add-email-button" class="action add">
                            <span><?= /* @escapeNotVerified */ __('Add') ?></span>
                        </button>
                    <?php endif; ?>
                </div>
            </div>

            <?php if ($block->isInvitationMessageAllowed()): ?>
                <div class="field text">
                    <label for="message" class="label"><span><?= /* @escapeNotVerified */ __('Message') ?></span></label>
                    <div class="control">
                        <textarea name="message" id="message" title="<?= /* @escapeNotVerified */ __('Message') ?>" placeholder="<?= /* @escapeNotVerified */ __('Message') ?>" class="input-text" rows="5" cols="5"></textarea>
                    </div>
                </div>
            <?php endif;?>
        </fieldset>

        <div class="actions-toolbar">
            <div class="primary">
                <button class="action submit primary" type="submit"><span><?= /* @escapeNotVerified */ __('Send Invitations') ?></span></button>
            </div>
            <div class="secondary">
                <a href="<?= /* @escapeNotVerified */ $this->helper('Magento\Invitation\Helper\Data')->getCustomerInvitationUrl() ?>" class="action back"><span><?= /* @escapeNotVerified */ __('Back to Invitations') ?></span></a>
            </div>
        </div>
    </form>

    <script id="add-email-friends-tmpl" type="text/x-magento-template">
    <fieldset class="fieldset">
        <div class="actions-toolbar">
            <div class="secondary">
                <button type="button" id="btn-remove<%- data._index_ %>" class="action remove"
                   title="<?= $block->escapeJs(__('Remove')) ?>">
                   <span><?= $block->escapeJs(__('Remove')) ?></span>
               </button>
            </div>
        </div>
        <div class="field email required">
            <label for="email_<%- data._index_ %>" class="label"><span><?= /* @escapeNotVerified */ __('Email') ?></span></label>
            <div class="control">
                <input name="email[<%- data._index_ %>]" id="email_<%- data._index_ %>"
                title="<?= /* @escapeNotVerified */ __('Email') ?>" value="" class="input-text" type="email"
                data-validate="{required:true, 'validate-email':true}"
                placeholder="<?= /* @escapeNotVerified */ __('Enter Email') ?>"
                 />
            </div>
        </div>
    </fieldset>
</script>
<?php else:?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You cannot send more invitations') ?></span></div>
    <div class="actions">
        <div class="secondary">
            <a href="<?= /* @escapeNotVerified */ $this->helper('Magento\Invitation\Helper\Data')->getCustomerInvitationUrl() ?>" class="action back"><span><?= /* @escapeNotVerified */ __('Back to Invitations') ?></span></a>
        </div>
    </div>
<?php endif; ?>
