<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Magento\Invitation\Block\Customer\ListCustomer
 */
?>
<div class="invitations">
    <?= $block->getChildHtml('list_before') ?>

    <?php if (count($block->getInvitationCollection())): ?>
        <div class="table-wrapper invitations">
            <table class="data table table-invitations" id="invitations-list-table">
                <caption class="table-caption"><?= /* @escapeNotVerified */ __('My Invitations') ?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col email"><?= /* @escapeNotVerified */ __('Email') ?></th>
                        <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($block->getInvitationCollection() as $invitation): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Email')) ?>" class="col email"><?= $block->escapeHtml($invitation->getEmail()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"> <?= /* @escapeNotVerified */ $this->helper('Magento\Invitation\Helper\Data')->getInvitationStatusText($invitation) ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php else: ?>
        <div class="message info empty"><span><?= /* @escapeNotVerified */ __('There are no sent invitations.') ?></span></div>
    <?php endif; ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a href="<?= /* @escapeNotVerified */ $this->helper('Magento\Invitation\Helper\Data')->getCustomerInvitationFormUrl() ?>" class="action send primary"><span><?= /* @escapeNotVerified */ __('Send Invitations') ?></span></a>
        </div>
        <div class="secondary">
            <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="action back"><span><?= /* @escapeNotVerified */ __('Back') ?></span></a>
        </div>
    </div>
</div>
