<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="widget block block-wishlist-search">
    <div class="block-title">
        <strong role="heading" aria-level="2"><?= /* @escapeNotVerified */ __('Wish List Search') ?></strong>
    </div>
    <div class="block-content">
        <?php if ($block->useSearchFormSelect()) : ?>
        <fieldset class="fieldset">
            <div class="field required find">
                <label for="<?= /* @escapeNotVerified */ $block->getBlockId() ?>-search_by" class="label"><span><?= /* @escapeNotVerified */ __('Search By') ?></span></label>
                <div class="control">
                    <?= /* @escapeNotVerified */ $block->getSearchFormSelect() ?>
                </div>
            </div>
        </fieldset>
        <?php endif;?>
    <?php if ($block->useNameForm()) : ?>
        <form id="<?= /* @escapeNotVerified */ $block->getBlockId() ?>-wishlist-quick-search-widget-name-form"
              action="<?= /* @escapeNotVerified */ $block->getActionUrl() ?>"
              method="get"
              class="form form-wishlist-search" <?php if ($block->useSearchFormSelect()) : ?>style="display:none;"<?php endif;?>
              data-hasrequired="* <?= /* @escapeNotVerified */ __('Please enter at least two letters.') ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <div class="field required name">
                    <label for="<?= /* @escapeNotVerified */ $block->getBlockId() ?>-quick_search_firstname" class="label"><span><?= /* @escapeNotVerified */ __('First Name') ?></span></label>
                    <div class="control">
                        <input type="text" class="input-text" data-validate="{required : true, minlength : 2}" id="<?= /* @escapeNotVerified */ $block->getBlockId() ?>-quick_search_firstname" name="params[firstname]">
                    </div>
                </div>
                <div class="field required lastname">
                    <label for="<?= /* @escapeNotVerified */ $block->getBlockId() ?>-quick_search_lastname" class="label"><span><?= /* @escapeNotVerified */ __('Last Name') ?></span></label>
                    <div class="control">
                        <input type="text" class="input-text" data-validate="{required : true, minlength : 2}" id="<?= /* @escapeNotVerified */ $block->getBlockId() ?>-quick_search_lastname" name="params[lastname]">
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <input type="hidden" name="params[search]" value="type">
                        <button type="submit" title="<?= $block->escapeHtml(__('Search')) ?>" class="action search"><span><?= /* @escapeNotVerified */ __('Search') ?></span></button>
                    </div>
                </div>
            </fieldset>
        </form>
    <?php endif; ?>

    <?php if ($block->useEmailForm()) : ?>
        <form id="<?= /* @escapeNotVerified */ $block->getBlockId() ?>-wishlist-quick-search-widget-email-form"
              action="<?= /* @escapeNotVerified */ $block->getActionUrl() ?>"
              method="get"
              class="form form-wishlist-search" <?php if ($block->useSearchFormSelect()) : ?>style="display: none;"<?php endif;?>
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <div class="field required email">
                    <label for="<?= /* @escapeNotVerified */ $block->getBlockId() ?>-quick_search_email" class="label"><span><?= /* @escapeNotVerified */ __('Owner Email') ?></span></label>
                    <div class="control">
                        <input type="text" class="input-text required-entry validate-email"  id="<?= /* @escapeNotVerified */ $block->getBlockId() ?>-quick_search_email" name="params[email]">
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <input type="hidden" name="params[search]" value="email">
                        <button type="submit" title="<?= $block->escapeHtml(__('Search')) ?>" class="action search"><span><?= /* @escapeNotVerified */ __('Search') ?></span></button>
                    </div>
                </div>
            </fieldset>
        </form>
    <?php endif; ?>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "[id='<?= /* @escapeNotVerified */ $block->getBlockId() ?>-search_by']": {
                "wishlistSearch": {
                    "nameFormSelector": "#<?= /* @escapeNotVerified */ $block->getBlockId() ?>-wishlist-quick-search-widget-name-form",
                    "emailFormSelector": "#<?= /* @escapeNotVerified */ $block->getBlockId() ?>-wishlist-quick-search-widget-email-form"
                }
        }
    }
</script>
