<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Magento\Reward\Block\Customer\Reward\History
 */
?>
<div class="block block-reward-history">
    <div class="block-title">
        <strong><?= /* @escapeNotVerified */ __('Balance History') ?></strong>
    </div>
    <div class="block-content">
        <?php if ($history = $block->getHistory()):?>

        <?= $block->getChildHtml('pager') ?>

        <div class="table-wrapper reward-history">
            <table class="data table table-reward-history">
                <caption class="table-caption"><?= /* @escapeNotVerified */ __('Balance History') ?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col balance"><?= /* @escapeNotVerified */ __('Balance') ?></th>
                        <th scope="col" class="col amount"><?= /* @escapeNotVerified */ __('Amount') ?></th>
                        <th scope="col" class="col points"><?= /* @escapeNotVerified */ __('Points') ?></th>
                        <th scope="col" class="col reason"><?= /* @escapeNotVerified */ __('Reason') ?></th>
                        <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Date') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($history as $item): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Balance')) ?>" classs="col balance"><?= /* @escapeNotVerified */ $block->getPointsBalance($item) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Amount')) ?>" classs="col amount"><?= /* @escapeNotVerified */ $block->getCurrencyBalance($item) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Points')) ?>" classs="col points"><?= /* @escapeNotVerified */ $block->getPointsDelta($item) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Reason')) ?>" classs="col reason">
                            <?= $block->escapeHtml($block->getMessage($item)) ?>
                            <?php if ($explanation = $block->getExplanation($item)):?><br /><small><?= $block->escapeHtml($explanation) ?></small><?php endif;?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" classs="col date">
                            <span class="datetime"><?= /* @escapeNotVerified */ $block->getDate($item) ?></span>
                            <?php if ($expirationDate = $block->getExpirationDate($item)):?>
                            <small><?= /* @escapeNotVerified */ __('Expires on %1', $expirationDate) ?></small>
                            <?php endif;?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>

        <?= $block->getChildHtml('pager') ?>

        <?php else:?>

            <div class="message info empty"><span><?= /* @escapeNotVerified */ __('There is no balance history.') ?></span></div>

        <?php endif;?>
    </div>
</div>
